openvehicles/Open-Vehicle-Monitoring-System-3

- vehicle/OVMS.V3/main/metrics_standard.h
Also a test to see if I can actually push stuff to the repo...
> Corrected apparently duplicated MOTOR to BATTERY then MOTOR.

- vehicle/OVMS.V3/components/vehicle_kiasoulev/component.mk
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.h
- vehicle/OVMS.V3/main/Kconfig
The initial stub for Kia Soul EV.
> Kia Soul EV: Initial stub

- vehicle/OVMS.V3/components/can/can.cpp
- vehicle/OVMS.V3/components/can/can.h
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Bug fix to on-off metric & charger status handling.
Store charger state in the relevant metrics.
Port the Ah and Hx polling from v2.
> Nissan Leaf Charger Status, Ah & Hx

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Expose some leaf specific metrics and configuration options
> Nissan leaf range configurable

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/can/src/canlog.cpp
- vehicle/OVMS.V3/components/can/src/canlog.h
- vehicle/OVMS.V3/components/ovms_ota/src/ovms_ota.cpp
- vehicle/OVMS.V3/components/sdcard/src/sdcard.cpp
- vehicle/OVMS.V3/components/sdcard/src/sdcard.h
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
- vehicle/OVMS.V3/knownissues.txt
- vehicle/OVMS.V3/main/ovms_command.cpp
- vehicle/OVMS.V3/main/ovms_housekeeping.cpp
- vehicle/OVMS.V3/main/ovms_semaphore.cpp
- vehicle/OVMS.V3/main/ovms_semaphore.h
- vehicle/OVMS.V3/todo.txt
Fixed problem setting charge state.
> Kia Soul Branch

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Add instrument soc and new car soc metrics.
Make configurable which to use for the main soc metric, defaulting to the instrument cluster's soc
> Nissan leaf soc instrument

- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.h
Removed notifications from KiaSoul that is now handled by Vehicle.
Added Emergency Alert notification on and off.
Also added pincode setting for commands like lock, unclock, open trunk, open charge door and a few others.
> Kia Soul- Pincode and notification

- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_can_send.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.h
Commands using pin are now checked against pin registered using OVMS#
config set password pin 1234.
> Kia Soul: Commands secured with pin.

- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_commands.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_incoming_c_can.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_web.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.h
- Added Kia Soul web configuration: Features, Battery
- Trip returns distance in units based on users settings.
- Corrected LDC-metrics.
- Changed Ticker1 in order to do less processing when car is off and
hopefully save the 12V battery.
> Kia Soul: Web-config, LDC-metrics fixed

- vehicle/OVMS.V3/components/vehicle_thinkcity/src/vehicle_thinkcity.cpp
- vehicle/OVMS.V3/components/vehicle_thinkcity/src/vehicle_thinkcity.h
This is an untested initial port from V2
> Implemented initial porting from V2

- vehicle/OVMS.V3/components/vehicle_thinkcity/src/tc_web.cpp
- vehicle/OVMS.V3/components/vehicle_thinkcity/src/vehicle_thinkcity.cpp
- vehicle/OVMS.V3/components/vehicle_thinkcity/src/vehicle_thinkcity.h
- Fixing negative values for current and temperatures
- Using polling framework to get some of the temperatures
- Webdashboard reconfigure to match the values for Think City
- Web UI - initial not working commit for some future functionality
> Various fixes and additions for Think City

- vehicle/OVMS.V3/components/ovms_webserver/src/ovms_webserver.cpp
- vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp
- vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg_init.cpp
- vehicle/OVMS.V3/components/ovms_webserver/src/web_displays.cpp
Without these changes the Webserver doesn't compile when any of these components is disabled.
> Fix compiling with OTA, Modem and/or servers disabled

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
Some of the other commands have a separate command for on and off (valet for example) but for climate control in v2 we did one command with an argument so I did that here too
> Add climate control to command framework

- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_commands.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_incoming_c_can.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_web.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.h
Fixed issues with the new standard BMS module.
Added new command, xks tripch, which displays trip data since last charge
> Kia Soul: Bms battery cells and trip counter from last charge

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Stale constants work different from how I initially understood them.
These charge counts actually remain valid even when the car is unused for several days/weeks. So no reason for the metric to go stale...
> Nissan Leaf: metrics motor rpm

- vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_commands.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_web.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.h
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.h
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_commands.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_web.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
- Fixed TPMS for NIRO
- Added history based range calculation for Niro
- Minimized polling and spread out polling on Niro to prevent CAN Write to clog up.
- Added AUX SOC for Soul
- Added AUX Battery Monitor for Kia Niro.
> Kia Niro and Kia Soul - Stability improvements, AUX Battery Monitor, Range calculation

- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.h
- vehicle/OVMS.V3/components/vehicle_smarteq/component.mk
- vehicle/OVMS.V3/components/vehicle_smarteq/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
- vehicle/OVMS.V3/main/Kconfig
new Vehicle Smart 453 4.gen based on Renault Zoe can bus but not all.
Basic functions added: SOC, ODO, SPEED, Temp, Charging Status...
> Add New Vehicle Smart ED/EQ 453 Gen.4

- vehicle/OVMS.V3/components/ovms_location/src/ovms_location.cpp
and use plural format for locations line
> Include GPS sat count in location status report

- vehicle/OVMS.V3/components/ovms_location/src/ovms_location.cpp
- vehicle/OVMS.V3/components/ovms_webserver/docs/index.rst
(It's funny to me that I didn't notice this!)
> A little more plural is needed.

- vehicle/OVMS.V3/components/vehicle_nissanleaf/docs/index.rst
- More info and links / video how to unplug TCU
- Clarify model years 
- Fix URL's 
- Add resources
> Docs: Nissan LEAF unplug TCU info, URL's etc..

- vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_commands.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_web.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.h
Detect charging from BMS relay and BMS ignition
Add support for right hand drive
Add support for odometer in miles
Add more info to VIN decoding
Add Kona to car name
Simulate charge door for Kona
Simulate AC charging current for Kona
Fixes #280,#277,#278
> Hyundai Kona improvements

- vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp
- vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp
> Ensure peer count is reset to 0 when clients disconnect

- vehicle/OVMS.V3/components/powermgmt/powermgmt.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_commands.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.h
move RegisterCanBus(2, CAN_MODE_ACTIVE, CAN_SPEED_500KBPS); to wakeup funktion..
> SmartED: fix for issue #293

- docs/source/userguide/vfs.rst
Adding some documentation to the users guide about the options for network transfers to and from VFS.  Included http and SCP.
> add doc about accessing files remotely

- vehicle/OVMS.V3/components/vehicle_nissanleaf/docs/index.rst
- Added more sections about 40/62kWh LEAFs, 
- Tidied up the document a bit too, now the battery section comes last, and model year first.
- Added link to .DBC files
> Update README file with more battery specs

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/docs/bmsdiag.rst
- vehicle/OVMS.V3/components/vehicle_smarted/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_smarted/docs/metrics.rst
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_commands.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_web.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.h
and a fix for long can poll response
> SmartED: add BMS diagnose report

- vehicle/OVMS.V3/components/duktape/src-input/duk_js_call.c
- vehicle/OVMS.V3/components/duktape/src-separate/duk_js_call.c
- vehicle/OVMS.V3/components/duktape/src/duktape.c
(the inline version of duktape that pulls in duk_js_call.c)
> quiet "maybe-uninitialized" error in ducktape.c

- plugin/abrp/abrp.rst
Explain how to get your own token and paste it in source code (in the rst file)
> Adding explanation on abrp login

- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
> Odometer fix

- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
Add comfort variables (fan speed, vent type, intake type)
Add door lock status (beta)
> Add some variables, fixes

- plugin/abrp/README.rst
- plugin/abrp/sendlivedata2abrp.js
ABRP version 1.1 fix and update:
- fixed the utc refreshing issue
- send notifications
- send live data only if necessary
> ABRP plugin fix and update (v1.1)

- plugin/abrp/README.rst
- plugin/abrp/sendlivedata2abrp.js
Version 1.2 updates:
- based now on OVMS configuration to store user token, car model and url
- review messages sent during charge
- send a message when vehicle is on before moving to update abrp
> abrp plugin v1.2

- vehicle/OVMS.V3/components/simcom/src/simcom.cpp
- vehicle/OVMS.V3/main/metrics_standard.cpp
- vehicle/OVMS.V3/main/metrics_standard.h
This allows detection of registration problems
> Expose Network Registration state via a new metric (m.net.mdm.netreg)

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Fix issue CAN write issue observed by @glynhudson  Nissan LEAF P312A DTC & dashboard warning light #409
> NL: implement use of can write parameter to allow/block TX writes

- vehicle/OVMS.V3/components/vehicle_vweup_obd/src/vehicle_vweup_obd.cpp
Had a bracket issue on the formula for energy used total: corrected
> VWUP.OBD: correct v.b.energy.used.total calculation

- vehicle/OVMS.V3/components/vehicle_vweup/src/t26_eup.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/t26_eup.h
Simplified the code and made lights and locked detection stable.
> VWUP.T26: Bugfix lights and locked detection 

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
I found this when I had my vehicle type set wrong.
> Don't set the vehicle to ready if it's unknown.

- vehicle/OVMS.V3/components/retools_pidscan/src/retools_pid.cpp
- vehicle/OVMS.V3/components/retools_pidscan/src/retools_pid.h
Analysis of the log messages was difficult, so doing it this way seems more sensible.
> Store the responses of the PID scan and output as part of the status.

- vehicle/OVMS.V3/components/vehicle_vweup/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_vweup/src/t26_eup.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/t26_eup.h
Some minor bugfixes and a little correction to the documentation.
Also prepared the code for evtl. future command implementations.
> VWUP.T26: Bugfix estimated range, remote command updates, edited documentation.

- vehicle/OVMS.V3/components/vehicle_mgev/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_can_handler.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_obd_pids.h
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_peps.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_states.h
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
Now supports "zombie" mode when the car is woken by the charger.
> MG: Complete re-write of the poll states and keep alives

- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_bms.cpp
It seems our cell voltage measurements were possibly incorrect, a better estimate is given with this calculation.
> MG: Change cell voltage conversion.

- vehicle/OVMS.V3/components/vehicle_voltampera/src/vehicle_voltampera.cpp
- lock/unlock status determinated by bit value, not a whole byte
- log of lock/unlock source
- set doors, trunk, hood, lighting metrics
> VA: fix lock/unlock for Volt 14 MY, set doors and lighting metrics

- docs/source/userguide/metrics.rst
- vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp
- vehicle/OVMS.V3/main/metrics_standard.cpp
- vehicle/OVMS.V3/main/metrics_standard.h
separate PR only for maintenance metrics as discussed.
> new metrics for maintenance/service, transmit via server v2

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.h
Changed:
components/vehicle_vweup/src/vweup_t26.cpp
components/vehicle_vweup/src/vweup_t26.h
> VWEUP: T26 -Minor bugfix preventing wake up when car is on plus beautified code

- README.md
> Corrected main README for unified VWUP

- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_web.cpp
Changed:
components/vehicle_vweup/src/vehicle_vweup.cpp
components/vehicle_vweup/src/vweup_t26.cpp
components/vehicle_vweup/src/vweup_web.cpp
> VWUP: Enhanced pre-heating range to 15 to 30 degrees

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
> VWUP (T26): Pre-heating temperature set correctly while switching pre-heating off

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Use actual bits for fanspeed, remove unused code and old todo comment
> NL: Simplify fan speed read

- vehicle/OVMS.V3/components/vehicle_vweup/docs/index_t26.rst
Changed:
vehicle/OVMS.V3/components/vehicle_vweup/docs/index_t26.rst
> VWUP: Corrected T26A documentation

- vehicle/OVMS.V3/components/vehicle_vweup/docs/index.rst
Changed:
components/vehicle_vweup/docs/index.rst
> VWUP: Corrected view on html example code in documentation

- vehicle/OVMS.V3/components/vehicle_bmwi3/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.cpp
- vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.h
Adjust polling intervals
Private metric xi3.s.age - how many minutes since we receieved fresh data from car
Doc tweak to document that and car behaviour when charging.
> bmwi3: Polling tweaks 

- vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.cpp
Hi,
Some little tweaks to polling intervals from a practical test.
Steve
> Tweak polling intervals

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
> VWUP: T26 - Added correct 12v metrics

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
> VWUP: T26 - Corrected charging12v false while pre-heating with turning ignition on

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
> VWUP: T26 - Bugfix charging12v

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
> VWUP: T26 - Some minor tweaks on 12v communication from T26 to OBD

- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
Changed:
vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
> VWUP: T26 - Rewrite 12v charging off detection

- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.h
- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
Changed
vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.h
> VWUP: T26 - Introduced t26_car_awake

- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
Only added a few lines of code to allow the display Charge kWh during a charge. Takes a while to show on the app as it needs to go over 1kWh of charge to trigger the display
> Cumulative charge energy

- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
Fixed bug causing code not to compile
> Fixed bug in vehicle_mgev.cpp. Stopping compile

- vehicle/OVMS.V3/components/vehicle_cadillac_c2_cts/src/vehicle_cadillac_c2_cts.cpp
- vehicle/OVMS.V3/components/vehicle_chevrolet_c6_corvette/src/vehicle_chevrolet_c6_corvette.cpp
chevrolet_c6_corvette: Minor formatting changes
> cadillac_c2_cts: Manage ms_v_env_on to avoid theft/flatbed alert

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_obd.cpp
> VWeUP/OBD: set charge duration to 0 on charge stop

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_obd.cpp
> VWeUP/OBD: add service notifications

- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
Changed:
components/vehicle_vweup/src/vehicle_vweup.cpp
> VWUP: Corrected sohfactor from 100 to 1 if 0

- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_bms.cpp
Undo changes to SOC calculations which accidentally went into this branch.
> Reverse changes to soc calculations not ready for release

- vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp
- vehicle/OVMS.V3/components/esp32can/src/esp32can.h
- vehicle/OVMS.V3/components/esp32can/src/esp32can_regdef.h
Also detect and reject invalid BRP values
> Add support for 33K, 50K, and 83K if we're an ESP32 V2 or higher

- docs/source/userguide/wifi.rst
- vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.cpp
- vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.h
@dexterbg meant for this to go into the master as well but wasn't sure how new PR's were working across v3.3 and master, cheers Derek
> Wifi: default to 20Mhz bandwidth

- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_web.cpp
Sorry, forgot to push the changes to mg_web.cpp. Have cloned and built the branch.
> Added missing file changes

- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.cpp
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.h
new code for added metrics and app support
> Maxus update

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/med3_web.cpp
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.cpp
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.h
Tab and page added for charging and cell metrics
> Web interface page added

- vehicle/OVMS.V3/components/ovms_location/src/ovms_location.cpp
(the reported location goes from: A,B -> A,B -> 0,B -> 0,A -> A,B -> A,B)
> Suppress false theft alerts due to a suspected SIMCOM GPS bug

- vehicle/OVMS.V3/components/vehicle_jaguaripace/component.mk
- vehicle/OVMS.V3/components/vehicle_jaguaripace/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_can_handler.cpp
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_obd_pids.h
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_poll_bcm.cpp
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_poll_becm.cpp
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_poll_hvac.cpp
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_poll_states.h
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_poll_tcu.cpp
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_poll_tpms.cpp
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/vehicle_jaguaripace.cpp
- vehicle/OVMS.V3/components/vehicle_jaguaripace/src/vehicle_jaguaripace.h
- vehicle/OVMS.V3/main/Kconfig
This is a first batch of files for the Jaguar IPace integration
> First v0.0.1 for the Jaguar IPace vehicle

- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_obd.cpp
> reformat energy and coloumb factors for vw e-UP

- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_configuration.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_web.cpp
When Config/Vehicle - Distance units: is set to Miles, MG/Battery config: Sufficient Range shows miles not km. 
MG/Charging Metrics now shows miles and km.
> Battery config - Range displays in Miles

- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_configuration.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_web.cpp
Switches MG/Battery Config/Sufficient Range adjustment to Miles if Miles selected in Config/Vehicle
Added Miles displays to MG/Charging Metrics page
> MG:Battery config in miles

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Updated to code align with extra detail in #620
> NL: improved new metric naming

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Most V2X metrics populated, more work required to incorporate into ovms app
> NL: alpha V2X implementation

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_voltampera/src/va_notify.cpp
- vehicle/OVMS.V3/components/vehicle_voltampera/src/vehicle_voltampera.cpp
- vehicle/OVMS.V3/components/vehicle_voltampera/src/vehicle_voltampera.h
new config: [xva] notify_va_metrics 	(bool, default no)
> - VA: added notification for the "fuel" metric.

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle/vehicle.h
OK, second attempt with a freshly rebased branch :) Please let me know if anything needs to be changed.
> vehicle: add inverter/motor energies to trip report

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
> #678 - add timerwait notification

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Noticed while testing on various LEAFs that it doesn't always wake them up. Added another message that helps :)
> Improve wakeup message

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/med3_pids.h
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/med3_web.cpp
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.cpp
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.h
Add CCS charging and re write polling system
> Add CCS charging

- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
SmartEQ polling update and fix for cell voltage request
> SmartEQ: BMS cell Monitor fix

- docs/source/userguide/console.rst
Thanks to @slcasner for providing the  WolfSSL version detail.
> Update SSH Console doc for OpenSSH 8.8 after WolfSSL 4.6.0 update

- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.cpp
- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.h
- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/xr4mon.htm
This release is now running stable on my car and I feel it's ready for others to use. It only reads the Tesla CAN bus, not the Toyota CAN bus, and it only displays information. It does not send any commands to the car.
> RAV4 EV Stable Release-Tesla Bus Read-Only

- .gitignore
- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.cpp
- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.h
- vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/xr4mon.htm
Final updates to Tesla-Only version. Subsequent contributions will also involve the Toyota bus on second CAN bus.
I don't know why the zlib was changed in my build environment. the .gitignore was an attempt to block that from being contributed upstream.
> RAV4 EV updates

- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_commands.cpp
Honestly, https://youtu.be/rR4n-0KYeKQ?t=21
Credit to Eva S.#4574 for compacting my original patch idea
> Fix Kia Soul Vin Checker?

- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
Adjust time to charge to Range Limit to account for battery SOH
> Improve time to charge to Range Limit

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_commands.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_commands.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_commands.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
- vehicle/OVMS.V3/components/vehicle_renaulttwizy/src/rt_charge.cpp
- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/rz_commands.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_commands.cpp
- Uses Metrics ->IsDefined() rather than checking for "-"
> Fix issue with use of char * after std::string deallocated in multiple places

- vehicle/OVMS.V3/components/vehicle_chevrolet_c6_corvette/src/vehicle_chevrolet_c6_corvette.cpp
- vehicle/OVMS.V3/components/vehicle_chevrolet_c6_corvette/src/vehicle_chevrolet_c6_corvette.h
> Chevrolet C6 Corvette: Leverage spontaneous PIDs to avoid polling when the car is off.

- docs/source/userguide/console.rst
- docs/source/userguide/logging.rst
- docs/source/userguide/scripting.rst
- docs/source/userguide/vfs.rst
> document deprecation of scp protocol in scp command

- vehicle/OVMS.V3/main/ovms_utils.h
Fix a small regression accidentely introduced in ecec210
> dbc : fix a regression on sign extension

- vehicle/OVMS.V3/main/ovms_metrics.cpp
- Use functions for km <--> mi conversions for int and float conversions that have better precision.
- Adds some extra conversions between all length metrics  (feet, metres, miles, km)
> Metrics - Improve accuracy/consistency km <--> mi and other length conversions

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
A few fixes to make the metric name more consistent.
> Ioniq 5 - Make custom metric naming more consistent

- vehicle/OVMS.V3/main/ovms_metrics.cpp
- vehicle/OVMS.V3/main/ovms_metrics.h
- Adds kWh/100km, km/kWh, and miles/kwh to metrics.. and conversions between them all.
> Add commonly used power consumption units to Metrics

- vehicle/OVMS.V3/components/vehicle_fiat500/docs/index.rst
Updated the documentation based upon the use of OVMS on my Fiat 500e (validated via the iOS/Android app)
> Update Fiat 500e documentation.

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_web.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h
Confirmed some a few more values and moved them to the new fetching framework.
Increase the top voltage for the dashboard.
Fix a bad 'case' statement in the Legacy 'feature' fetch.
> Ioniq 5 - some small fixes

- vehicle/OVMS.V3/components/vehicle_minise/src/vehicle_minise.cpp
Better initialization.
Code cleanup.
> Small fixes for Mini Cooper SE vehicle.

- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_web.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
- vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/rz2_web.cpp
- vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/vehicle_renaultzoe_ph2_obd.cpp
Fix web pages registration/unregistration for Renault Zoe Phase 2 and Mitsubishi
> Fix web pages registration/unregistration

- docs/source/userguide/installation.rst
> Add SIM card to items to have.

- vehicle/OVMS.V3/components/ovms_webserver/src/web_framework.cpp
> Slider Widget - Fix disabling when loading up with check-box unchecked

- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
Added v_pos_trip metric for MGEV vehicle
> Add Trip Metric

- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_commands.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_web.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.h
- Convert divisions to multiplications
- Supply new standard metrics
- Persist metrics fix
- Fix charge metrics if crash during charge session
- Add support for trip distance from speed
> Trio tweaking

- vehicle/OVMS.V3/main/ovms_metrics.cpp
- vehicle/OVMS.V3/main/ovms_metrics.h
This can be tested in TPMS by changing temperature and/or pressure to imperial measurements
>  Fix conversion of vector metrics when getting a vector 

- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_web.cpp
Fixed a missing line in mg_web.cpp.
> Fix Wwb Dashboard

- vehicle/OVMS.V3/components/can/src/canlog.h
- vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
- vehicle/OVMS.V3/components/vehicle_renaulttwizy/src/vehicle_renaulttwizy.h
- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/rz_commands.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_commands.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
A few headers were missing, these turned into errors in ESP-IDFv5+
> missing headers

- vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp
- vehicle/OVMS.V3/components/ovms_ota/src/ovms_ota.cpp
- vehicle/OVMS.V3/main/ovms_peripherals.cpp
- vehicle/OVMS.V3/main/ovms_version.cpp
Some changes, or replacement, of header files are needed.
> ESP-IDF v5+: change in header files

- vehicle/OVMS.V3/.gitignore
- vehicle/OVMS.V3/dependencies.lock
- vehicle/OVMS.V3/main/idf_component.yml
Cf https://components.espressif.com/components/espressif/mdns
> ESP-IDF v5+ : adding mdns 1.0.8 external dependency

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h
Following it being added in  https://github.com/Esprit1st/Hyundai-Ioniq-5-Torque-Pro-PIDs/blob/main/TorqueIONIQ5AWD77kWh.csv
> Ioniq 5 - Read 'Requested Charge Current' value

- docs/source/userguide/events.rst
- docs/source/userguide/metrics.rst
- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/obd2ecu/src/obd2ecu.cpp
- vehicle/OVMS.V3/components/obd2ecu/src/obd2ecu.h
- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle/vehicle.h
- vehicle/OVMS.V3/main/metrics_standard.cpp
- vehicle/OVMS.V3/main/metrics_standard.h
- Adds metric m.obd2ecu.on
- adds events obd2ecu.start, obd2ecu.stop
- Add bd2ecu change-notification virtual methods
> Add metric+events for obd2ecu on/off

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_commands.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.cpp
- Kia/Hyundai Common make sure it records charing active
- Ioniq 5 - Fix updating of charge status.
> Ioniq 5 - fix recording of charging in trip counter.

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp
> Change cellular signal quality logging level to DEBUG

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_commands.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h
- vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.cpp
Bump version with fixes to
* Battery monitor to trigger polling
* Range estimation while charging 
* Indicator & hazard support
* General Responsiveness
* Responsiveness while Obd2Ecu is on.
> Ioniq5 Fixes v0.0.5

- vehicle/OVMS.V3/components/console_ssh/src/console_ssh.cpp
Reverts openvehicles/Open-Vehicle-Monitoring-System-3#891
> Revert "compatibility with WolfSSH >= 1.4.12"

- docs/source/userguide/installation.rst
- docs/source/userguide/locations.rst
- vehicle/OVMS.V3/components/ovms_webserver/docs/metrics.rst
- vehicle/OVMS.V3/components/vehicle_minise/docs/index.rst
Some warnings were raised during documentation build and have been fixed.
> fix a few documentation issues

- vehicle/OVMS.V3/components/vehicle_mgev/CMakeLists.txt
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mg5.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgzsev2.cpp
Changes to be able to compile using ESP-IDF5 in the future
> MG-EV: ESP-IDF5 Changes

- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/vehicle_renaultzoe.cpp
- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/vehicle_renaultzoe.h
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.h
Reverts openvehicles/Open-Vehicle-Monitoring-System-3#905
> Revert "Zoe + Smart ED - Move static locals to member variables"

- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/vehicle_renaultzoe.cpp
- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/vehicle_renaultzoe.h
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.h
After my last bodged attempt at this where I left artifacts where I'd extracted this change from the middle of a larger merge, I have made sure this definitely compiles.
> Zoe + Smart ED - Move static locals to member variables

- vehicle/OVMS.V3/components/vehicle_byd_atto3/CMakeLists.txt
- vehicle/OVMS.V3/components/vehicle_byd_atto3/component.mk
- vehicle/OVMS.V3/components/vehicle_byd_atto3/src/vehicle_byd_atto3.cpp
- vehicle/OVMS.V3/components/vehicle_byd_atto3/src/vehicle_byd_atto3.h
- vehicle/OVMS.V3/main/Kconfig
Initial support for the BYD Atto 3
* Battery SOC
* Charge power
* AC or DC charging
* Some Dashboard support
> Add BYD Atto 3

- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_configuration.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.h
Reverts openvehicles/Open-Vehicle-Monitoring-System-3#937
> Revert "Fix bms dod limits"

- vehicle/OVMS.V3/components/ovms_ota/src/ovms_ota.cpp
- vehicle/OVMS.V3/components/ovms_webserver/src/web_framework.cpp
- vehicle/OVMS.V3/components/vehicle_smarted/src/ed_commands.cpp
- vehicle/OVMS.V3/main/ovms_boot.cpp
- vehicle/OVMS.V3/main/ovms_command.cpp
- vehicle/OVMS.V3/main/ovms_housekeeping.cpp
- vehicle/OVMS.V3/main/ovms_module.cpp
- vehicle/OVMS.V3/main/ovms_time.cpp
- vehicle/OVMS.V3/main/ovms_vfs.cpp
- localtime -> localtime_r
- gmtime -> gmtime_r
- asctime -> asctime_r
> Move to thread-safe time functions

- vehicle/OVMS.V3/main/ovms_metrics.cpp
- Change "utc" unit name (in the UI) to "utctime"
- Fix JSON Output
- Tidy code to use switch() for readability and add necessary cases.
- Add reverse conversion for TimeLocal to TimeUtc
- Add parsing of string
> UTCTime/LocalTime - Various fixes to units and conversion

- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
- Fix 12V battery current reading (only newer cars)
- Fix charge efficiency calculation
> MiEV Update

- vehicle/OVMS.V3/main/ovms_metrics.h
- Some overrides were marked virtual
- Mark all overridden methods with 'override'
> Metrics - Clarify which virtual methods are overridden

- vehicle/OVMS.V3/main/ovms_metrics.cpp
- vehicle/OVMS.V3/main/ovms_metrics.h
- Name (as const char *) in map was pointing to stack memory in metric arrays.
moving to std::string does use more memory but don't see a way around this.
> Metrics - handle registering of array elements properly

- vehicle/OVMS.V3/components/ovms_plugins/CMakeLists.txt
- vehicle/OVMS.V3/components/ovms_plugins/src/ovms_plugins.cpp
- vehicle/OVMS.V3/main/ovms_metrics.cpp
- vehicle/OVMS.V3/main/ovms_netmanager.cpp
Found a few areas that failed to compile with various modules disabled
> Fix compile with reduced feature set

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_mgev/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_configuration.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/mg_web.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mg5.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mg5.hpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.cpp
Added code for the MG5 49kWh variant. A Version page has been added to allow user to select the vehicle variant.
> Add Mg5 short range variant

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_renaultzoe/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/rz_commands.cpp
- vehicle/OVMS.V3/components/vehicle_renaultzoe/src/rz_web.cpp
add Cabin Pre-heat/cool Control
> Renault Zoe Ph1

- vehicle/OVMS.V3/components/vehicle_nissanleaf/docs/index.rst
Add note about remote locking/unlocking.
Spelling fixes.
> Small updates to Nissan Leaf Documentation

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
add VW e-Up change info
prevent charge attempts when unplugged
> VWUP: changes.txt & bugfix

- README.md
This download source is overseen quickly. See: https://github.com/openvehicles/Open-Vehicle-Android/issues/165
> Update README.md - add link for direct Android APK download

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_commands.cpp
- vehicle/OVMS.V3/main/ovms_metrics.h
Fix alignment of outputs.
Output default metric units.
> Fix ioniq5 tpms output

- vehicle/OVMS.V3/main/ovms_metrics.cpp
- vehicle/OVMS.V3/main/ovms_metrics.h
- A bunch of methods don't really have any reason being virtual and certainly are not overridden.
> Metrics - Pare down vtable of OvmsMetric class.

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_commands.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_web.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
The Ioniq 5 configuration appears to work fine for EV6
> Ioniq5 add ev6 descriptions

- vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp
- vehicle/OVMS.V3/components/poller/src/vehicle_poller.h
- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle/vehicle.h
Start with poll sequence 0
Remove unused call-backs 
Ignore setting top-level state to same value
> Poller tweaks

- vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp
- vehicle/OVMS.V3/components/poller/src/vehicle_poller.h
- vehicle/OVMS.V3/components/poller/src/vehicle_poller_isotp.cpp
- vehicle/OVMS.V3/components/poller/src/vehicle_poller_vwtp.cpp
Looking at reducing unnecessary poller task loop processing to reduce time per incoming payload
> Poller - Short-cut protocol handling if there is no response pending

- vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp
- vehicle/OVMS.V3/components/poller/src/vehicle_poller.h
- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle/vehicle.h
- vehicle/OVMS.V3/main/ovms_utils.h
- Trying hard to avoid race conditions.
- Signal loops so that we can shut down.
> Vehicle Shutdown - Wait for loop shutdowns and close down as nicely as possible

- vehicle/OVMS.V3/components/poller/src/vehicle_poller_isotp.cpp
- vehicle/OVMS.V3/components/poller/src/vehicle_poller_vwtp.cpp
- Fixes critical issue where the multiframe polls were not able to complete due to the protocol # being zeroed.
> Poller - Only try the next poll if the current multiframe is done.

- vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp
Small tweak.  It's probably not a big deal as the chance of tearing is low
> Poller - Make sure the overflow counters are thread safe

- vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp
- vehicle/OVMS.V3/components/poller/src/vehicle_poller.h
- vehicle/OVMS.V3/main/ovms_utils.h
Use the MyBoot shutdown register when shutting down tthe poller & vehicles.
> Poller - Use Shutdown Register while shutting down

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle/vehicle.h
I'm not sure whether the m_pending list is just way overkill... but given that it's mostly empty it maybe ok?
Feedback welcome.
> Vehicle - Cleaner swap / shutdown of vehicle

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_smarteq/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
add 5min Booster preheat cool
add TPMS pressure
add Internal Temp
add Doors status
> Smart EQ 453 - prehead and cool funktion

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/can/src/canlog_vfs.cpp
- vehicle/OVMS.V3/components/dbc/src/dbc_app.cpp
- vehicle/OVMS.V3/components/ovms_ota/src/ovms_ota.cpp
- vehicle/OVMS.V3/components/ovms_plugins/src/ovms_plugins.cpp
- vehicle/OVMS.V3/components/ovms_script/src/ovms_script.cpp
- vehicle/OVMS.V3/main/ovms_command.cpp
- vehicle/OVMS.V3/main/ovms_command.h
- vehicle/OVMS.V3/main/ovms_config.cpp
- vehicle/OVMS.V3/main/ovms_vfs.cpp
- vehicle/OVMS.V3/main/ovms_vfs.h
Add completion for vfs command line.
> VFS - Add file completion

- docs/source/userguide/vfs.rst
- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/main/glob_match.cpp
- vehicle/OVMS.V3/main/glob_match.h
- vehicle/OVMS.V3/main/ovms_vfs.cpp
Note this uses a third-party matching function provided by Joshua J Baker under the MIT license
> Add simple '*' and '?' globs to VFS functions  ls, rls and rm

- vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp
Fix compilation error introduced in 2915281af0715a46de548f80a0104d4d9492e400 / #1032
> fix compilation error

- docs/source/userguide/scripting.rst
- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duktape.cpp
- vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duktape.h
- vehicle/OVMS.V3/main/ovms_command.cpp
- vehicle/OVMS.V3/main/ovms_command.h
- Command map moved to std::string (by necessity)
- Implement proper shut-down of duktape
> Duktape - Finish Implementing console commands

- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp
- vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.h
- vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
improve handling of sufficient SoC
add detection of faulty selector lever microswitch
> VWEUP: fix sufficient SoC, add selector lever detecion

- docs/source/userguide/scripting.rst
- vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duktape.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
- vehicle/OVMS.V3/main/ovms_command.cpp
- vehicle/OVMS.V3/main/ovms_command.h
- only allow user commands to be added at certain points.
- auto-create 'usr' command
- allow 'usr' command for root command and against xhiq
- do some checks on the user-command names allowed.
> Duktape - Implement security for user console commands

- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_can_send.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_commands.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp
- vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h
Disable unused 'write' code
Refine scope of logs for polling (add v-ioniq5-poll)
Fix some scope of procedures (to match base class)
> Ioniq5 code tidy

- vehicle/OVMS.V3/components/vehicle_zombie_vcu/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_zombie_vcu/src/vehicle_zombie_vcu.cpp
- vehicle/OVMS.V3/components/vehicle_zombie_vcu/src/vehicle_zombie_vcu.h
Adding ZomberVerter VCU documentation page, and adding some metrics to the integration as well as addressing the warnings
> Adding ZomberVerter VCU documentation page

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
> Add digits of precision switch for efficiency

- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- vehicle/OVMS.V3/components/vehicle/vehicle.h
good for comparing different regular routes as to which is the fastest one :)
this time with better data types and display (thanks to Michael) :D
> add trip time to trip report

- docs/source/userguide/scripting.rst
- vehicle/OVMS.V3/components/vehicle/vehicle.cpp
fix accidentally deleted precision code in trip report :-(
> fix trip report

- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mg5.cpp
- vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
Added PIDs to enable Gateway Module Polling.
Will not turn polling off when vehicle is turned off.
Add PID for new SoC processing and remove old batterySoC PID.
Adjusted Charging Threshold preset down a little.
> Mg5 updates

- vehicle/OVMS.V3/components/can/src/can.cpp
- vehicle/OVMS.V3/components/can/src/can.h
- vehicle/OVMS.V3/components/can/src/canlog_monitor.cpp
- vehicle/OVMS.V3/components/retools/src/retools.cpp
- Fix issue with RemoveFilter
- Add some checks for correctness
- Use busno integer instead of ascii values for filtering.
- Improve the parsing
> Can filter fixes

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_smarteq/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
Added:
- timebased heating (Web UI -> Features)
- recharge 12V when 12V alert raised (Web UI -> Features)
- switch GPS off when parking for power saving and reactivate GPS every 50 minutes for 10 min. to get new position (Web UI -> Features)
- maintance data: date, days, km and level (Web UI -> Status)
- fixed negative ambient/HV temperature
- calculate v.b.cac and v.b.capacity
- modem network can locked to LTE only (Web UI -> Features)
- gear shift -> metrics
- charge duration auto switch between OCS and math (Web UI -> Features)
> completely overhauled vehicle_smarteq (SQ)

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_smarteq/docs/index.rst
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
fixed:
- Ambient/HV temperature issue, showed sometime 6500°C
- added Check if Cellular activated
- change some double digit to float digit in math operations
- added forgotten DDT4all enable option at Features Website
- at Website config renamed ED/SQ to EQ. My fault I overrided this.
> fixed reported smart EQ issues

- README.md
- docs/source/userguide/homeassistant.rst
@dexterbg  Please have a look.
> Add Home Assistant integration documentation

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
Removed not needed `MyConfig.SetParamValueBool("xsq", "gps.off", false)`
Set Firmware download link to Dexter's Web EDGE Version, some memeber of smart-EMOTION.de community are confused which one is the latest FW.
Optimized Modem Networktype option auto to no preferred Network
Fixed Cmd Wakeup2
> Fixing some smartEQ settings

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_nissanleaf/docs/index.rst
Fix for the documentation issues related to #1119
> Fix for Leaf ZE1 documentation

- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
reset v.c.kwh only at new charging session
> Fix for smart EQ v.c.kwh reset

- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
Reduction of minimum pressure for incorrect value
> smart EQ: fix TPMS Alert

- vehicle/OVMS.V3/changes.txt
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
Update smart EQ notifications
- Optional extended data
- Charging Information fix for iOS
- New notification for pre-conditioning
- Various information commands added
- Fixed TPMS values; values ​​were reset to zero when parking
- renamed OCS to OBD
> Update smart EQ notifications

- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- sends a success/failure notification
Ambient light activation
- true = unv 37
- false = unv 36
> smart EQ: updated DDT4all option

- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
DDT4all:
- Changed from notification to response
- Changed the DRL + Tail code to a more compatible code
> smart EQ: updated DDT4all

- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- set Climate/Heater system to default false
- add a enable/disable switch for Climate notification
> smart EQ update Web UI & Climate notify

- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
- vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
>  Bringing 2011-2012 Leaf ZE0 to a working state #1176 

- vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
- vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
Reverts openvehicles/Open-Vehicle-Monitoring-System-3#1213 due to build issues / interdependency with PR #1214
> Revert "Refactor SmartEQ poll reply handling and metrics"
