openvehicles/Open-Vehicle-Monitoring-System-3

vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Fix bug in stat v2 server message
Fill in more of the environment v2 server messages
Ported more Nissan Leaf code from v2
Should the doors unions defined in the v2 server be in the .cpp file or the .h? They're private and don't need to be exposed to the rest of the code base.
Is there already better way to do the car off detection, which of my suggestions, if any, is most appropriate?
=> Nissan leaf

vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp
The TPMS message on v2 looks like:
MP-0 W0,0,0,0,0,0,0,0,-1
But the v3 module was sending
MP-0 W0,,0,,0,,0,,0
This pull request sets a default value for all the fields and avoids the crash.
=> Server V2: Avoid android client crash in TPMS message

vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp
You could argue strncpy isn't needed here because we allocated a buffer sized by strlen, so we know the buffer is big enough (or is null if new fails, and the world is about to end, I guess?). Either way, leaving out the null terminator on the string leads to mangled messages, as we transmit data until we find a null in memory.
=> Fix too short strncpy in v2 command responses

vehicle/OVMS.V3/main/ovms_events.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp
Erasing an iterator from the list invalidates the iterator (I guess because the memory for the backing object has been released) so you can't erase and then increment. This construction with a while loop is a bit messy but there's not much advantage to trying to keep the iterators in loop scope in these small function.
I have not audited the code for other examples of this faulty pattern
=> Fix crash when deregistering metric listeners and event listeners

vehicle/OVMS.V3/components/vehicle_teslaroadster/src/vehicle_teslaroadster.cpp
Looks like a simple paste error on rear TPMS metrics.  Fixed.
=> Fixed rear TPMS metrics (structure name typo)

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Set ms_v_env_on from 0x60d[1] (ms_v_env_awake still follows activity of 0x284).
Fix ms_v_env_temp conversion to °C.
Make multiplex check for ms_v_bat_temp more precise.
Remove setting odometer units (always reports km).
=> Nissan Leaf:

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Fix commit 7600b09616dd58023e815824c19648dbe35774ef by checking only the specific bit relevant to units.
Tested by me on 2015 (UK) and by Tom on 2012 and 2016 (JP).
=> Get units for odometer reading from 0x355 byte 6 bit 5.

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
An additional factor of 10000 was accidentally introduced in 76f6d65d.
=> Nissan Leaf: remove additional division by 10000 in CAC

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Use the Nissan native facility to turn off climate control after it is started remotely. Replaces the same functionality implemented in the OVMS. Thank you Stein Arne Sordal for providing the necessary information to use this feature.
=> Nissan leaf remote climate control off

vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
To restore some of the basic functionality of OVMS v3 for the i-MiEV, this pull request fixes the following:
- detecting the charging state
- detecting car on/awake
- handbrake (?) CAN bus code fix
I've tested it now for a few days, and it appears to work as in OVMS v2.
I'd like to review more of the i-MiEV code, and maybe even add further functionality, but the "re" framework currently crashes my OVMS module... I'll see if I can troubleshoot it.
(Anyway, please bear with me as this is the first time I'm diving into the OVMS code.)
=> Mitsubishi i-MiEV: bug fixes

vehicle/OVMS.V3/components/ovms_ota/src/ovms_ota.cpp, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp, vehicle/OVMS.V3/main/ovms_version.cpp, vehicle/OVMS.V3/main/ovms_version.h
Add GetOVMSPartitionVersion() to ovms_version.cpp which returns the OVMS versions for the specified partition (if possible). Change ota_status() and OvmsWebServer::HandleCfgFirmware() to display image versions for each partition.
=> Display partition image versions on the Firmware setup page and ota status output

vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp, vehicle/OVMS.V3/components/simcom/src/gsmnmea.cpp, vehicle/OVMS.V3/components/simcom/src/gsmnmea.h, vehicle/OVMS.V3/components/simcom/src/simcom.cpp, vehicle/OVMS.V3/components/simcom/src/simcom.h, vehicle/OVMS.V3/components/vehicle_fiat500/src/vehicle_fiat500e.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp, vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp, vehicle/OVMS.V3/components/vehicle_renaulttwizy/src/vehicle_renaulttwizy.cpp, vehicle/OVMS.V3/components/vehicle_thinkcity/src/vehicle_thinkcity.cpp, vehicle/OVMS.V3/components/vehicle_voltampera/src/vehicle_voltampera.cpp, vehicle/OVMS.V3/components/vehicle_zeva/src/vehicle_zeva.cpp
Currently some vehicles force the OVMS GPS and thus the simcom to be enabled. Even when the users disables GSM and GPS via the web config it gets enabled. In fact various vehicle ports required gps, even though the only one using it seems to be the Twizy with its gps logging.
This pull request simply removes the "anti-feature" of forced gps & simcom.
This is sort of a design decision PR, so the following represents my point of view:
This reminds me a lot of the ["the program controls the user"](https://youtu.be/7twCCWjSnMg?t=57) term, introduced by Richard Stallman. Even though we give the user a choice to enable or disable GPS and the simcom module we ignore that decision and make the OVMS do what we want it to do, i.e. let it control the user. So by having this the OVMS acts a lot like …
=> Respect the users decision whether to enable or disable gps

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Fix for #162
Turns out the PollReply for the battery info is 41 bytes long on these models instead of the 39 bytes we have previously seen on the 24KWh models.
The contents still seem to have the same structure as before, it is just that 2 unidentified bytes are added to the end of the reply.
=> Fix for 0% SOH on 30KWh models with Nissan BMS update

vehicle/OVMS.V3/components/dbc/component.mk, vehicle/OVMS.V3/components/dbc/src/dbc_tokeniser.l
FreeBSD uses Berkeley Yacc (byacc) but we need to use bison. It might be better to define YACC (and LEX) at a higher level in case other lex and modules are added but I don't understand how to do that with gmake.
While we're here quiet flex "defined but not used" yyunput and input warnings in dbc_tokeniser.l.
=> Fix build on FreeBSD and quiet lexer compile warnings

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Report SOH from passive 0x5b3 in private metric "xnl.v.b.soh.instrument".
Report SOH from active 0x7bb.6101 in private metric "xnl.v.b.soh.newcar".
Standard metric "v.b.soh" copies from "xnl.v.b.soh.instrument" by default,
or from "xnl.v.b.soh.newcar" if config option "xnl.soh.newcar" is set to "true".
=> Chose between two SOH metrics.

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_types.h, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Added web pages for configuration of:
* Main parameters: modelyear and maxgids (as 24kwh or 30kwh selection)
* Battery: target charge goal as SOC % or as range in km
Pages are based on similar functionality for Renault Twizy and Kia Soul.
Note that this is related to to functionality requests #180 (auto detect model year) and #181 (auto detect max gids). Though the code in this pull request does not do an auto detect, it should be noted that at this moment nobody has described a robust way to do such an auto detect. 
It is unlikely we will find a suitable method for auto detect of modelyear (even when based on VIN). So this config setting remains valid.
It is likely that we will get a reliable method to detect max gids / battery size (for instance via the battery voltages/temeratures). At …
=> Nissan Leaf: add web config pages for parameters and battery

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
"xnl.v.b.type": Attempt to auto-detect battery type and size.  Uses active poll, so only updates when car is on.
"xnl.v.c.duration": report all 6 charge duration estimates in minutes.
"xnl.v.c.duration.label": meaning of the 6 charge duration estimates.
"xnl.v.c.quick": an extra charge duration estimate, only updates during quick charging.
"xnl.v.b.soc.nominal": SOC% from 0x5bb, accurate to 1 decimal place, and hopefully works with all model years.
=> More Leaf battery metrics:

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
On a 30kwh leaf, the metrics for GIDs, battery energy available and battery energy capacity were randomly switching from actual value to maximum value.
=> Nissan Leaf: battery metrics for 30kwh

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Originally the metric would be continuously set during a drive. 
A recent code change from me made that this was only done once as the car was turned on/off. However, the unintended result is that the metric will go stale during the drive.
Now adapted the code so that initializations for going into drive mode are only done once while the metric is continuously refreshed.
=> Nissan Leaf: prevent v.e.on from going stale

vehicle/OVMS.V3/components/ovms_webserver/src/web_framework.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp
Allow to configure the following settings in a way that makes it clear to 'normal' users what these settings do and mean:
- xnl.soc.newcar
- xnl.soh.newcar
- xnl.maxGids
- xnl.newCarAh
Also made a minor change in the generic code to allow for an html input box with empty label.
=> Nissan Leaf: Config page set SOC and SOH options

vehicle/OVMS.V3/components/can/src/can.cpp, vehicle/OVMS.V3/components/can/src/can.h, vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp, vehicle/OVMS.V3/components/mcp2515/src/mcp2515.cpp
Only the ESP2515 can buses are supported right now so disallow these speeds with esp32can. Finally, detect and report when "can canN start" fails.
=> Add support for 33.333kHz and 83.333kHz single wire can speeds.

docs/source/userguide/ecu.rst
I presume since there's links to FastTech to get the OVMS module, it's ok to have it here too.
=> "standard" OBD2ECU cable is now available

vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.h
Fix for Kia e-Niro hangs OVMS when car is off and no charging.
Fix for speed reading.
Wake up polling when car starts to charge again.
=> Fix for Kia e-Niro

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/powermgmt/component.mk, vehicle/OVMS.V3/components/powermgmt/powermgmt.cpp, vehicle/OVMS.V3/components/powermgmt/powermgmt.h, vehicle/OVMS.V3/components/powermgmt/powermgmt_web.cpp, vehicle/OVMS.V3/components/pushover/src/pushover.cpp, vehicle/OVMS.V3/components/pushover/src/pushover.h, vehicle/OVMS.V3/components/swcan/src/swcan.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.cpp
- Configuration via Web UI
- Switch off SIMCOM and WiFi after certain (configurable) time period of idling/non-charging of 12V battery has lapsed.
- Turn on previously switched off modules if 12V charging is initiated.
- If 12V battery alert is received, shut down all the modules and OVMS after certain configurable grace period (default 30 minutes)
=> PowerMgmt: New Power Management module

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Add defines for 40kWh battery pack. These batteries are becoming more and more popular as a retrofit to older Leafs, so it's high time to add this to OVMS
=> Add 40kWh GIDS and AH defines

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp
Add the 40kWh GIDS and AH numbers to the UI so that users can take them into use more easily. For this PR to get merged, the previous "patch-1" needs to be merged first.
=> Add 40kWh option to UI

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
No UI changes yet, but it's good to have the defines ready. We'll be seeing 62kWh adopters of this app soon, especially since the Nissan app works so "intermittently" to say the least.
=> Add 62kWh Leaf GIDS and AH defines

vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.cpp
This will make DNS in the DHCP server (as seen by tools like Fing) match what is seen in MDNS
Currently this shows up as "espressif" which is annoying if you have let the Internet-of-things take over your house and have many poorly named ESP devices.
=> Set the Vehicle ID as the hostname for the DHCP request parameter

plugin/abrp/sendlivedata2abrp.js
abrp javascript example: Set the timer to a lower frequency (60s) and simplify code using AsFloat() metrics function instead of Value()
=> abrp: fix timer and read data as float

vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp
False notifications were received when regenerating, due to the code going into charging mode.
=> Fix false charge messages

vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.cpp, vehicle/OVMS.V3/components/spinodma/spi_master_nodma.c
components/esp32wifi/src/esp32wifi.cpp
Change from deprecated WIFI_PS_MODEM to WIFI_PS_MIN_MODEM in
esp32wifi::SetPowerMode()
components/spinodma/spi_master_nodma.c
Remove older spi_signal_conn_t struct definition and use the
one in soc/spi_periph.h
=> Some non-invasive changes towards esp-idf v4.0

vehicle/OVMS.V3/components/vehicle_mercedesb250e/component.mk, vehicle/OVMS.V3/components/vehicle_mercedesb250e/src/vehicle_mercedesb250e.cpp, vehicle/OVMS.V3/components/vehicle_mercedesb250e/src/vehicle_mercedesb250e.h, vehicle/OVMS.V3/main/Kconfig
Passivel listener for CAN1.
Decodes only small set of messages, for example momentary power and ODO are found, but no SOC.
=> Initial support for Mercedes B250E

vehicle/OVMS.V3/main/metrics_standard.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
Use the RTC_NOINIT_ATTR attribute to put some metrics in RTC slow memory
These persist across crashes, firmware updates, and warm reboots and
are zero'ed on cold reboots
This is only implemented for OvmsMetricFloat
Unrelated fix: puts() -> writer->puts() in metrics_list()
=> Make some metrics persistent across warm reboots

docs/source/userguide/metrics.rst, vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/main/metrics_standard.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
Make some more metrics persistent as per Michael:
v.b.energy.used, v.b.energy.recd, v.c.temp, v.i.temp
Add v.e.cabintemp while we're at it
Check that persistent metric name fits in the field
Add -p to metrics_list() to limit output to just persistent metrics
and improve argument handling (e.g. "metrics list -vp v.p" works)
invalidate pmetrics by zero'ing magic instead of size ("metrics persist -r")
no need to increment pmetrics version since we changed the size
update changes.txt and add minimal documentation to the user guide
=> Persistent metrics improvements

vehicle/OVMS.V3/main/ovms_metrics.cpp
Use the m_value field to cache it as suggested by Michael
(This actually cleans things up compared to pre-persistent metrics)
=> Reduce RTC persistent metrics reads of slow RAM

vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
Add -S to metrics list that display defined metrics as "metrics set" commands. Combined with -p this is handy for pmetrics dev work.
Add a persistent metrics shutdown check. If any problems are found the entire pmetrics struct is reinitialized from in memory values.
Remove OvmsMetric::IsPersist() and use the public m_persist member instead.
Simplify log formatting in OvmsMetricFloat::OvmsMetricFloat().
=> Check persistent metrics at shutdown

vehicle/OVMS.V3/components/vehicle_vweup/src/t26_eup.cpp
PR has been created on Android app to support display cabin temp instead of PEM temp using correct metric https://github.com/openvehicles/Open-Vehicle-Android/pull/111
=> VWUP: use correct metric for cabin temp now app support

vehicle/OVMS.V3/components/vehicle_mgev/src/mg_can_handler.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_bms.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
The PEPS module reports that the car is locked when it is running (even if it isn't).  Therefore revert the logic to check if the car is on first before checking if it's locked.  However, this requires us to be a bit more careful about when we poll the BCM to avoid alarms.
=> MG: Fix SoC polling when the car is running

vehicle/OVMS.V3/components/vehicle_vweup/docs/index.rst, vehicle/OVMS.V3/components/vehicle_vweup/src/t26_eup.cpp
Fixed ICCB detection, wrong values on estimated range, wrong values on cabin temperature and wrong locked/unlocked status when the doors were opened.
=> VWUP.T26: Fixed some minor bugs.

vehicle/OVMS.V3/components/vehicle_mgev/src/mg_can_handler.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_bms.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_vcu.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
We currently cause the charger port to be locked when the car is unlocked and detect zombie mode in a way that is dependant on the CAN hardware.  This resolves those issues.
=> MG: Handle charging in a more dignified way

vehicle/OVMS.V3/components/vehicle_mgev/src/mg_can_handler.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_vcu.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
Additional protection to avoid the 12v from draining.  Does not appear to always be able to detect a delayed charge anymore, but will not deplete the 12v battery, so better for a stable release.
=> MG: 12v protection

.travis.yml
Just needs Travis-CI.org to be configured for the repo and optionally a badge adding to the README.
=> CI: Add Travis-CI build script to build commits to the OVMS.V3 code.

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
- Cabin temperature readings seem to differ between cars. Added configurable offset in NL Features GUI.
- Added battery heater present (yes/no) metric as discussed in #311 `v.b.heaterpresent                        yes`
=> fix cabintemp, add battery heater metric

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
@mjkapkan thanks for adding the cabin temp offset, I have used the same approach to allow users to set AC charger voltages on newer Leafs. Note I shifted your offset to the "General" section and tweaked the wording to make it a bit clearer. Hope you're ok with that :)
=> NL: add user scaling for AC charger voltage

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
change from using fan speed as it can result in hvac reporting as on when it is not
=> NL: use setpoint to indicate hvac status

vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp
otherwise the decimals in the android app aren't of any use :)
=> ovms_server_v2: change charge current to float

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
Hi @mjkapkan, please try this on your 2013. I have looked at the d[1] byte to separate out the various climate control functions as follows: a7 .... a0
a7 = 0
a6 = 1 for fan
a4,a5 = 1 for cooling
a2,a3 = unsure but if byte is 0x08 or 0x04 climate control is off 
a1 = 1 for auto hvac mode
a0 = 1 for heating
fan speed d[4] reports even when climate control is off, so this needs to be set to zero from hvac status. I have gone back to hvac status reporting as on when ventilating, heating or cooling as climate control is on when d[1] is not 0x08 or 0x04.
=> NL: improved climate settings >2015

plugin/abrp/sendlivedata2abrp.js
Fix a small typo that took a while to diagnose why the module wasn't being found.
=> Fix typo in sendlivedata2abrp

vehicle/OVMS.V3/components/vehicle_vweup/docs/index.rst, vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.h, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_obd.cpp
Thanks for taking care of migrating the namespaces on the previous PR :)
Sorry to request another pull already, but I just found a stupid typo that causes the detection of the car state to loop when in obd-only mode :(
=> bugfix in obd only mode, add charging metrics

vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.cpp, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_web.cpp
The temperature range VW uses for the pre-heating cabin temperature is 16 to 30 degrees celcius.
We had set the temperatures between 18 and 23. This is now corrected to 16 - 30.
=> VWeUP/T26: Enhanched temp range for cabin pre-heating (16-30)

vehicle/OVMS.V3/components/vehicle/vehicle.cpp
Due to the use of a smoothed average, when v.b.power goes to zero the smoothed average v.b.consumption only tends to zero and eventually gives crazy numbers like 1e-45.
This change just chops the v.b.consumption down to 0 once it falls below 1.
=> Round v.b.consumption so as to avoid the tiny numbers that result from the moving average calculation

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Make it clear that type1 is ZE0 and type2 is AZE0. Also the L2 is 6.6kW, L1 is 200V and L0 is 100V. This matches with Nissans internal documents, so let's use the same.
=> NL: Update charge timer comments

vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
=> VWUP: T26 - Brought back 12v processing from version 0.1.2

vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.cpp, vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.h
- Reduce logging by moving all the logging of OBD data to verbose only
- Remove use of "idle" as a charger state
- Our private metrics don't get initialised when instantiated; leave it to be done by real data from car
- Fix the way I did v.e.awake and v.e.on to rather behave the way @dexterbg explained.
=> Some Sunday afternoon fixes for the bmwi3:

vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.h
- When sending all metrics we don't send those with no value.
Helps ensure we only feed valid data
- New updatetimes.  If they are not set they all use updatetime.idle
so behaviour doesn't change unless you set these:
updatetime.charging: update interval to use when the car is charging
updatetime.on: update interval to use when the car is on
updatetime.sendall: set this and all metrics will be sent at this interval
this is helpful for charting to make sure there are regular data points.
=> mqtt/v3: add more control of publishing intervals.  Also SendAll doesn't send metrics for which we have no value

vehicle/OVMS.V3/components/vehicle_mgev/src/mg_web.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h
The dashboard voltage needed to be increased as MG ZS EV goes to over 455V and Charge kW to 82kW. Also added code for BMS Cell monitor panel.
=> Added mg_web.cpp to change dasboard guages and BMS Cell Monitor

vehicle/OVMS.V3/components/ovms_netlib/src/ovms_netconns.cpp, vehicle/OVMS.V3/components/ovms_netlib/src/ovms_netconns.h, vehicle/OVMS.V3/components/ovms_netlib/src/ovms_nethttp.cpp, vehicle/OVMS.V3/components/ovms_netlib/src/ovms_nethttp.h
This adds support for connection timeouts (and fixes a race condition with the user data) but I don't think this class is actually used by anything.  Perhaps it should simply be removed?
=> Net: Support for connection timeout in NetConns.

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/ovms_ota/src/ovms_ota.cpp, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg_init.cpp
This removes the old HTTP client and uses the newer Mongoose HTTP client which then allows for HTTPS updates (and changelogs).
Despite adding TLS support to the update, the binary size increase is very small.
I considered whether it was worth moving the implementations out of the downloaders from `ovms_ota.cpp`, I welcome comments on the implementation.  In addition, I had to do a fair amount of fudging in my `WaitForCompletion` function to allow it to execute as part of a request.
=> OTA: Change to use NetHttp and therefore support TLS.

vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
These are a couple of changes I've made locally to improve support for my early 2010 i-MiEV. Specifically:
1.  I have found that the battery cell information in the 0x6e? CAN sentences was being misinterpreted, because the index byte 1 sometimes has a bit in the high order nybble set. I don't know what this bit indicates, but it breaks the battery monitoring so I've taken the simple expedient of masking it out. This might apply to later i-MIEVs too. 
2. The ignition status is carried in a 0x012 sentence rather than the 0x101 sentence on later vehicles. I've made the simplifying assumption that both sentences won't be seen in the one vehicle. 
The changes should be compatible with existing vehicles as far as I can see.
=> Early I-MiEV support

vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.cpp
this avoids overwriting the value now saved through persistence.
Did the same for v.e.awake though not sure it it is persisted.
Harmless if it is not.
=> Only initialise v.e.on in module startup if it currently has no value.

vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp, vehicle/OVMS.V3/components/esp32can/src/esp32can_regdef.h
Starting with revision 2, the function of bit 4 of the interrupt enable register changes from "enable wakeup interrupt" to "divide BRP by 2". The OVMS SJA1000 code enables "all interrupts except arbitration loss" which was causing can baud rates to be half of what they were set to.
Reported by Thomas Heuer who referenced:
- [https://www.esp32.com/viewtopic.php?t=15581#p59670](https://www.esp32.com/viewtopic.php?t=15581#p59670)
=> Minimal fix for ESP32 V3 can bus: turn off BRP_DIV if we're V2 or higher

vehicle/OVMS.V3/components/vehicle_nissanleaf/docs/index.rst
Clarifies how the Remote Climate Control feature doesn't work with Gen 1 LEAF and v3 hardware currently.
=> Clarify Remote Climate Control and Gen 1 LEAF

vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_obd.cpp
Coulomb: Volkswagen defines `0.0018204444`, which is closer to `3909375/2^31`
Energy: Volkswagen defines `0.0001165084`, which is closer to `250200/2^31`
Not sure if it makes sense to keep representing them in this way when it doesn't look as nice and even?
Also as we are on quite powerful hardware it might make sense to just use `double` everywhere?
=> update energy and coloumb factors for vw e-UP

vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.cpp, vehicle/OVMS.V3/main/ovms_command.h, vehicle/OVMS.V3/main/ovms_events.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h, vehicle/OVMS.V3/main/ovms_module.cpp, vehicle/OVMS.V3/main/ovms_utils.h, vehicle/OVMS.V3/main/ovms_vfs.cpp
Rename the -S flag to -c (show [c]ommand) for "metrics list" and add flags usage strings for it and "metrics persist". Add -t flag to display to display string metrics with semantics similar to linux "cat -t" which can be helpful when looking at metric strings with
unprintable characters.
Fix "metrics list" to search for at most one metric substring; previously the code would apply up to two "show only" arguments.
Add OvmsMetric::IsString().
Make OvmsCommand::PutUsage() public.
Check for invalid flags for "wifi scan", "event raise", "module factory reset", "vfs head", and "vfs tail".
Includes feedback and many suggestions from Michael and Stephen.
=> Flags cleanup: Add usage strings and detect/report invalid flags

vehicle/OVMS.V3/components/can/src/canformat_gvret.cpp
canformat_gvret_binary::PopulateBusList12() and canformat_gvret_binary::PopulateBusList3() were just multiplying
bus->m_speed by 1000; the MAP_CAN_SPEED() understands CAN_SPEED_33KBPS and CAN_SPEED_83KBPS
(I'm trying to get savvycan working with a 33.333k GMLAN and I'm pretty sure this is one of my problems)
=> Use MAP_CAN_SPEED() to get accurately return gvret 33.333 and 83.333 speeds

vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp
For reference, here is Michael's original issue: [https://github.com/espressif/esp-idf/issues/4276#issuecomment-548753085](https://github.com/espressif/esp-idf/issues/4276#issuecomment-548753085) and the commit of interest is [https://github.com/espressif/esp-idf/commit/2f5806092135e3d991057bc06225bdcf536e93a5](https://github.com/espressif/esp-idf/commit/2f5806092135e3d991057bc06225bdcf536e93a5)
Here is a reformatted description of this fix:
> TWAI_ERRATA_FIX_BUS_OFF_REC
> Add SW workaround for REC change during bus-off
>
> When the bus-off condition is reached, the REC should be reset to 0 and frozen (via LOM) by the driver's ISR. However on the ESP32, there is an edge case where the REC will increase before the driver's ISR can respond in time (e.g., due to the rapid occurrence of bus …
=> CAN: First attempt at porting the first of four espressif TWAI/CAN errata fixes

vehicle/OVMS.V3/components/ovms_location/src/ovms_location.cpp
Check for zero longitude too (also seen: A,B -> A,B -> A,0 -> A,B -> A,B)
=> Suppress false theft alerts due to a suspected SIMCOM GPS bug #2

docs/source/protocol_v2/messages.rst, vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp, vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.h, vehicle/OVMS.V3/main/ovms_utils.cpp
@dexterbg, Hi Michael, could you check whether the following is consistent with the rest of the V2 messaging framework. Is it necessary to include the "legacy keys" or just use the string versions of mode, state, substate? 
Is there anything else required to be updated to include the v.g metrics?
=> serverV2: add v.g metrics

vehicle/OVMS.V3/components/can/src/can.h, vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp
For reference, here is Michael's original issue:
https://github.com/espressif/esp-idf/issues/4276#issuecomment-548753085
The commit of interest is here:
https://github.com/espressif/esp-idf/commit/2f5806092135e3d991057bc06225bdcf536e93a5
Here is a reformatted description of this fix:
Errata workaround: TWAI_ERRATA_FIX_TX_INTR_LOST
Add SW workaround for TX interrupt lost
On the ESP32, when a transmit interrupt occurs, and interrupt
register is read on the same APB clock cycle, the transmit
interrupt could be lost. Enabling this option will add a
workaround that checks the transmit buffer status bit to
recover any lost transmit interrupt.
The fix involves keeping track of when the tx buffer is in use; look for TWAI_HAL_STATE_FLAG_TX_BUFF_OCCUPIED in:
esp/components/hal/twai_hal_iram.c
My …
=> CAN: Second of four espressif TWAI/CAN errata fixes: SW workaround for TX interrupt lost

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
This PR aims to improve three things
- 2011-2012 LEAFs are reported as plugged in all the time (Waiting for ZE0 user to test)
- 2011-2012 LEAFs now report measured AC voltage from CAN message 0x380 (Waiting for ZE0 user to test)
- 2013+ LEAFs now report 220V/110V instead of 200V/100V when charging on L1/L2
For now I have only tested this on my 2015 AZE0. There might be some codechange still needed to display AC voltage properly in app while charging for ZE0, and also we need to see if this fixes the "always plugged in" issue 476
=> NL: ZE0 charger fix, AC Voltage added, AZE0 cleanup

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h, vehicle/OVMS.V3/components/vehicle_renaulttwizy/doc/changes.txt
This PR does some cleanup and adds new metrics for the Nissan LEAF
- m_max_gids (Max number of GIDs the battery can reach (for 2016+))
- m_battery_heatrequested (Battery is requesting heater elements to turn on (for 2013+))
- m_battery_heatergranted (Vehicle is OKing heater elements to turn on (for 2013+))
- m_charge_minutes_3kW_remaining (The 3kW charge time estimate the car calculates)
- m_remaining_chargebars (Remaining charge "bars" on dashboard)
Further development should be done with the battery heating metrics, and alert the user once this is triggered. During colder than -17*C battery temperature, the battery will start to use its own power to heat itself up in the form of 300W heating elements. This will discharge the battery down to 30%SOC if left in the cold for too long, so it …
=> NL: Add new metrics

vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp
Fix for trip notification for Mitsubishi: (exclude 255 init value)
=> Mitsubishi trip range fix

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Removed unused variables from `HandleCharging()` which are now handled in `HandleChargeEstimation()`.
=> NL: fix compiler warnings

vehicle/OVMS.V3/components/can/src/canlog_tcpclient.cpp, vehicle/OVMS.V3/components/can/src/canlog_tcpclient.h
The implementation of the TCP client CAN logger is broken.
canlog_tcpclient->Open() does not wait for connection to be established and immediatly returns, making canlog_tcpclient->IsOpen() always return false, and thus the logger object to be deleted immediately.
I propose a patch that waits at most 10s until the connection is established.
=> Fix the TCP client CAN logger

docs/source/crtd/can_logging.rst, vehicle/OVMS.V3/components/can/src/canformat_canswitch.cpp
* the TAG was wrong for this format and has been fixed
* this format (`cs11`) is now metionned in [the documentation](https://docs.openvehicles.com/en/stable/crtd/can_logging.html#logging-to-sd-card)
=> fix `cs11` (canswitch) tag, and reference this format in the documentation (#728)

docs/source/crtd/can_logging.rst, vehicle/OVMS.V3/components/can/src/canformat_lawicel.cpp, vehicle/OVMS.V3/components/can/src/canformat_lawicel.h
Typo - this format name (`lawicel`, a.k.a. `slcan` in the Linux Kernel) comes from the LAWICEL AB company and its product : http://www.lawicel.com/can232/can232.pdf
=> rename `lawricel` format to `lawicel` (#728)

vehicle/OVMS.V3/components/vehicle_cadillac_c2_cts/src/vehicle_cadillac_c2_cts.cpp, vehicle/OVMS.V3/components/vehicle_cadillac_c2_cts/src/vehicle_cadillac_c2_cts.h
We only use two poll states, remove unused polltimes from the poll_pid_t list. Minor whitespace.
=> 2nd gen Cadillac CTS: Leverage spontaneous PIDs to avoid polling when the car is off.

vehicle/OVMS.V3/components/vehicle/vehicle_bms.cpp
Fix a (probably) copy-paste issue with cell temps
=> Vehicle - Fix RestartCellTemperatures to resize the correct vector

vehicle/OVMS.V3/components/dbc/src/dbc.cpp, vehicle/OVMS.V3/main/ovms_utils.h
When non-32-bits negative numbers were processed by the DBC processor, there was an issue where the resulting metric values were incorrect.
As an example:
A 16-bit signed value coming from the can bus as 0xFFF7(-9) is being multiplied by a factor of -1.
When handled by the DBC processor, the incoming number is stored as 0x0000FFF7 ; which is not -9, but 65527.
After multiplication, it comes as 0xFFFF0009(-65527).
(While those should be: 0xFFFFFFF7(-9) and 0x00000009(9))
The root cause is that the sign of the non-32-bit number is not extended to the left, thus making it a different number.
The fix is to sign-extend the number to the left (it should work from 2-bit numbers to 32-bit numbers) when we're dealing with signed numbers.
Signed-off-by: Ludovic LANGE …
=> fix negative integer DBC numbers having wrong values

vehicle/OVMS.V3/main/ovms_utils.cpp, vehicle/OVMS.V3/main/ovms_utils.h
One of the strengths of these buffer extraction tools is that they check to make sure the extractions are within bounds.  They also make very clear how many bytes are being extracted - something I had found confusing previously.
There are big-endian and little-endian versions, signed (with sign-extension thanks to Ludovic's discovering of the bug) and unsigned versions,  std::string  and uint8_t* versions.
There is also a slight improvement to the sign_extend (which I originally converted from macro to template and was credited for by Ludovic). I have added an overloaded sign_extend  that templates the sign-bit, shifting the bit arithmetic to compile-time.
=> Vehicle - Add buffer handling tools to ovms utils

vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle/vehicle_bms.cpp
Uses a strict (class) enum for the Battery and Temperature status rather than magic numbers in the code.
I didn't use the Enum for the Metric because I figured that was too big a change.
=> Vehicle - Use Enum for Bat/Temp status

vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle/vehicle_bms.cpp
This adds a method that copies out existing data - resets to a new configuration, and then copies it back in.
=> Add Method to change voltage cell arrangement, preserving existing data

vehicle/OVMS.V3/main/ovms_log.h
Adds ESP_BUFFER_LOG*  similar to ESP_LOG*  for dumping out logs using the internal esp_log buffer utilities.
=> Ovms Logs - Add macros for hex-dumping buffers

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle/vehicle_bms.cpp, vehicle/OVMS.V3/components/vehicle/vehicle_shell.cpp
- Allows for voltages and/or temperatures columns to be displayed depending on what's available.
- Wraps values for one module over multiple lines (where you have multiple cells per module) making it readable in a smaller display.
-  Have a maximum of 5 columns total
- Add commands  `bms temp` to display just temperature stats and `bms volt` to display just voltage stats.
=> Enhance BMS shell display

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/docs/index.rst, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h, vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/docs/index.rst, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.h, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp
The base modules had the power consumption doubled up with different metrics and using capitalisation and / characters.
This commit removes that from the base and inherited classes.  (An upcoming commit will allow access to metrics with different units)
=> Use new power metrics in Hyundai kia/ioniq 5

vehicle/OVMS.V3/main/ovms_config.cpp, vehicle/OVMS.V3/main/ovms_utils.cpp
`realpath()` has been [introduced in esp-idf 4.4](https://github.com/espressif/esp-idf/commit/d83ce227aa987d648e1a0dddba32b88846374815#diff-91b1abbc42db113c5dcf9c11c594f0b3e75cae5f6dfba9ef8b68e26bbd422f4a) and is useful to cleanup a path and check its existence.
We start using it in `OvmsConfig::ProtectedPath()`.
=> add `realpath()` (backport from esp-idf) and ensure path is canonical before use

docs/source/userguide/scripting.rst, vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
I have left this as a block of commits as a single pull-request as
* they really form a single feature of unit conversions in scripts.
* there as already been feedback on the output and form of the functions/commands.
The inclusion of FeetPSS is really a part of the metric/imperial conversions.  (needing a 'short distance' version of metres per second squared).
I think I've got all the documentation done.
=> Add Unit Conversions to shell and duktape scripts 

vehicle/OVMS.V3/main/ovms_vfs.cpp
When you have a deep directory structure it can sometime be useful to have a `tree`-like command to show all files / directories at once.
This implementation tries to do that, and adds the `vfs rls` command for that:
```
OVMS# vfs rls /store/
[DIR]     01-Jan-1980 00:00  /store/ovms_config/
Error: protected path
[DIR]     01-Jan-1980 00:20  /store/plugin/
9.8k  01-Jan-1980 00:20  /store/plugin/metrics
4.0k  01-Jan-1980 01:22  /store/plugin/metrics-table
5.8k  01-Jan-1980 01:23  /store/plugin/commands
29.9k  22-Oct-2022 23:13  /store/plugin/dashboard
[DIR]     01-Jan-1980 01:00  /store/dbc/
[DIR]     08-Nov-2022 23:35  /store/scripts/
[DIR]     08-Nov-2022 23:38  /store/events/
[DIR]     08-Nov-2022 23:40  /store/events/sd.unmounting/
27   09-Nov-2022 21:47 …
```
=> add a recursive ls `vfs rls` command

vehicle/OVMS.V3/components/can/src/canlog.cpp
if the message has not been able to be sent to the queue, we need to free() the msg.text memory that we just allocated with strdup()
(When the message is successfully sent to the queue, then the free() will occur when the message is retrieved.)
=> add a free() that seems to be missing

vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
Previously the metrics listeners were registered by storing the `caller` parameter
as a `const char *`.
This made mistakes possible when we would register and deregister with the same string
but not the same memory address.
This patch changes the `caller` parameter type to `std::string` which will prevent this kind
of mistakes.
For consistency with `OvmsEvents::RegisterEvent`, the second parameter to `OvmsMetrics::RegisterListener`
is also converted to `std::string`.
=> Change metrics listener registration parameter types

docs/source/crtd/can_logging.rst, docs/source/crtd/index.rst, docs/source/userguide/scripting.rst, vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/can/src/can.cpp, vehicle/OVMS.V3/components/can/src/can.h, vehicle/OVMS.V3/components/can/src/canformat_crtd.cpp, vehicle/OVMS.V3/components/can/src/canlog.cpp, vehicle/OVMS.V3/components/can/src/canlog.h, vehicle/OVMS.V3/components/can/src/canlog_monitor.cpp, vehicle/OVMS.V3/main/ovms_utils.h
This PR adds the ability to log some metrics to the CAN logs ; and allows the configuration of which events are going to be logged (event logging was already existent)
A new configuration item `can log.metrics_filters` allows to choose which metrics will be sent to the can logs.
The default configurations is NOT to log any metric.
The metrics are sent to the can log subsystem as events. When using the CRTD format for example, those will appear as `1CEV` lines.
The metrics are sent as a JSON object prefixed with `metric: `, having the following fields:
* `name` : the name of the metric
* `value`: the value of the metric in the default unit
* `unit`: the default unit of the metric
Example:
```
metric: { "name": "v.p.gpstime", "value": 1668730982, "unit": "Sec" }
```
Example in a CRTD file: …
=> add configurable metrics to CAN logs, and allows configuration of events

vehicle/OVMS.V3/components/can/src/canlog_vfs.cpp, vehicle/OVMS.V3/components/can/src/canlog_vfs.h, vehicle/OVMS.V3/main/ovms_utils.cpp, vehicle/OVMS.V3/main/ovms_utils.h, vehicle/OVMS.V3/main/ovms_vfs.cpp
This PR tracks (and displays) the current file size of opened CAN log files.
The file size is tracked in the `canlog_vfs_conn` class, and is displayed in `GetStats()` for both the `canlog_vfs_conn` class and the `canlog_vfs` class.
File size is then available as a result of command:
```
OVMS# can log status
#1: open Type:vfs Format:crtd(discard) Vehicle:DEMO Path:/sd/logs/autolog/autolog.crtd Size:6.9k Messages:82 Dropped:0 Filtered:0 Rate:0.0%
/sd/logs/autolog/autolog.crtd: running Size:6.9k Messages:82 Discarded:0 Dropped:0 Filtered:0 Rate:0.0%
```
Having the file size available is a pre-requisite for #748 if we want to split files by size.
=> Can log track file size

vehicle/OVMS.V3/components/ovms_http/src/ovms_http.cpp, vehicle/OVMS.V3/components/ovms_netlib/src/ovms_nethttp.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duk_http.cpp, vehicle/OVMS.V3/main/ovms_utils.h
I had some issues fetching OTA firmware from some servers (S3-compatible buckets), because of the headers that were all lower-case.
In that case, the OvmsHttpClient returns a size of 0, and the OTA fails with:
```
Error: Expected download file size (0) is invalid
```
As HTTP Header fields names are case-insensitive, having a case-insensitive comparison means that we can be compatible with more servers.
=> OvmsHttpClient : case-insensitive comparison of `Content-Length` header

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/ovms_location/src/ovms_location.cpp, vehicle/OVMS.V3/components/ovms_tpms/src/ovms_tpms.cpp, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg_init.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle_bms.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_commands.cpp, vehicle/OVMS.V3/main/ovms_config.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h, vehicle/OVMS.V3/main/ovms_utils.cpp, vehicle/OVMS.V3/main/ovms_utils.h
This series of patches adds the ability for a user to configure the units they want for the various types of metrics.  It extends the simple km/M configuration to Speed, acceleration, Pressure etc.
The general 'metric list' as an option to show user-configured units.
The TPMS shell modules will now use the user-configured units.  I think this should be the way it works, however I'm also prepared to have the default as it was and to have a (-u) option to show TPMS in user-configured units (or vica versa).
=> Add user-configurable unit support

vehicle/OVMS.V3/components/strverscmp/component.mk
We have a local implementation of `strverscmp` ; however ESP-IDF seems to include it in newlib since version 4.x
(I'm not 100% sure but at least in 4.4 it is present)
A small test allows to include or not the component.
Tested on both our local fork of ESP-IDF and release 4.4
See #360
=> condition `strverscmp` inclusion to the version of ESP-IDF

vehicle/OVMS.V3/components/sdcard/src/sdcard.cpp
GCC 8.4.0 does not accept an assignment with the macros [`SDMMC_HOST_DEFAULT()`](https://github.com/espressif/esp-idf/blob/8153bfe4125e6a608abccf1561fd10285016c90a/components/driver/include/driver/sdmmc_host.h#L30) and [`SDMMC_SLOT_CONFIG_DEFAULT()`](https://github.com/espressif/esp-idf/blob/8153bfe4125e6a608abccf1561fd10285016c90a/components/driver/include/driver/sdmmc_host.h#L92), because the macros are defined as a curly braces list ; it fails with `error: no match for 'operator=' (operand types are 'sdmmc_host_t' and '<brace-enclosed initializer list>')`
This patch fixes the syntax so that it works with GCC 8.4.0, by prepending the type before the list. GCC 5.2.0 is OK with the fix.
See #360
=> change assignment of sdcard members to appease GCC 8.4.0

vehicle/OVMS.V3/components/vehicle/vehicle.cpp
Fix display of metrics in the status trip command  if they are set to default. 
Initialise the energy used and received so it doesn't display bad values when first initialised.
=> Fix vehicle status command display

vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp
The signature of function `xTaskCreatePinnedToCore` was not referencing the type `TaskHandle_t`, so it would cause an error when this type changes in future ESP-IDF versions.
=> ESP-IDF v5+: change type of TaskHandle_t

vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniqvfl/src/ioniqvfl_web.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniqvfl/src/vehicle_hyundai_ioniqvfl.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniqvfl/src/vehicle_hyundai_ioniqvfl.h, vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.h, vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.cpp, vehicle/OVMS.V3/components/vehicle_maxus_edeliver3/src/vehicle_med3.h, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h, vehicle/OVMS.V3/components/vehicle_renaulttwizy/src/vehicle_renaulttwizy.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe/src/vehicle_renaultzoe.h, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/vehicle_renaultzoe_ph2_obd.h, vehicle/OVMS.V3/components/vehicle_smarted/src/vehicle_smarted.h, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h, vehicle/OVMS.V3/components/vehicle_toyotarav4ev/src/vehicle_toyotarav4ev.h, vehicle/OVMS.V3/components/vehicle_vweup/src/vehicle_vweup.h, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_obd.h, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_web.cpp
When compiling without the webserver component (obviously an uncommon situation), a few part of the code are not guarded with defines - this fixes that.
=> ESP-IDF v5+: dependency on ovms_webserver.h

vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.cpp
`wifi_interface_t` is more or less equivalent to `esp_interface_t` and the values are the same, however in terms of argument type it's more consistent to use `wifi_interface_t` for `esp_wifi_set_bandwidth()` and `esp_wifi_get_mac()`.  
Cf:
* redefinition:
* https://docs.espressif.com/projects/esp-idf/en/v3.3.6/api-reference/network/esp_wifi.html?highlight=wifi_event#id4
* https://docs.espressif.com/projects/esp-idf/en/v4.2.3/esp32/api-reference/network/esp_wifi.html#_CPPv416wifi_interface_t 
* no more present:
* https://docs.espressif.com/projects/esp-idf/en/v4.3.3/esp32/api-reference/network/esp_wifi.html#_CPPv416wifi_interface_t
* https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv416wifi_interface_t
Cf #806  / #810 
Signed-off-by: …
=> replace some constants with their more adapted counterpart

vehicle/OVMS.V3/components/vehicle_smarted/src/ed_can_poll.cpp, vehicle/OVMS.V3/main/ovms_boot.cpp
The missing header is important for ESP-IDF > 3.
The function signature is incorrect, and while it's only a warning, in ESP-IDF > 3 warnings are treated as errors.
Cf #806 / #810
=> Add header and fix function signature

vehicle/OVMS.V3/components/esp32can/src/esp32can.h, vehicle/OVMS.V3/components/mcp2515/src/mcp2515.cpp, vehicle/OVMS.V3/main/ovms_peripherals.cpp
This change is compatible with 3.3.x.
=> ESP-IDF v4+ : esp_intr.h is deprecated, replaced by esp_intr_alloc.h

vehicle/OVMS.V3/components/vfsedit/src/openemacs.c
May not be the best way, but removes the warning.
(In ESPv4+, warnings are treated as errors by default)
=> remove warning : '_GNU_SOURCE' redefined

vehicle/OVMS.V3/components/console/commands.c
Both are very similar (but not equal) in 3.3:
* https://github.com/espressif/esp-idf/blob/release/v3.3/components/esp32/include/rom/queue.h
* https://github.com/espressif/esp-idf/blob/release/v3.3/components/newlib/include/sys/queue.h
Starting with 4.4, rom/queue.h is officially deprecated in favor of sys/queue.h:
https://github.com/espressif/esp-idf/blob/release/v4.4/components/esp32/include/rom/queue.h
=> remove warning by replacing rom/queue.h with sys/queue.h

vehicle/OVMS.V3/main/ovms_command.cpp, vehicle/OVMS.V3/main/ovms_command.h, vehicle/OVMS.V3/main/ovms_utils.h
This kind of warning gives an error in ESP-IDF v5+
=> ESP-IDF v5+: static assertion failed: comparison object must be invocable as const

vehicle/OVMS.V3/main/ovms_metrics.h, vehicle/OVMS.V3/main/ovms_notify.h
This kind of warning gives an error in ESP-IDF v5+
=> ESP-IDF v5+: static assertion failed: std::vector must have the same value_type as its allocator

vehicle/OVMS.V3/main/ovms_boot.cpp, vehicle/OVMS.V3/main/ovms_peripherals.cpp
Some bit size constants are already a back-compatible define and are removed in later ESP-IDF versions:
https://github.com/espressif/esp-idf/blob/v3.3.6/components/driver/include/driver/adc.h#L45-L53
=> changes to (long deprecated) ADC constants

vehicle/OVMS.V3/main/ovms.h
ESP-IDF 4.x renamed some constants (cf https://github.com/espressif/esp-idf/commit/51e66d0f8247fd8314458f8e209a93cb12823cf4) so we reintroduce them for compatibility with existing code.
Another solution would be to impact the said code (`main/ovms_boot.cpp`, `main/ovms_module.cpp`) with #ifdef.
=> ESP-IDF 4.x : impact of renamed constants

vehicle/OVMS.V3/components/vehicle_hyundai_ioniqvfl/src/ioniqvfl_web.cpp, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_web.cpp
`_GLIBCXX_USE_C99` is a private define, and its use triggers a warning in ESP-IDF >= 4
It seems that removing it in those version has no adverse effect.
=> ESP-IDF v4+ : cannot use this private define

vehicle/OVMS.V3/components/simcom/src/simcom_5360.cpp, vehicle/OVMS.V3/components/simcom/src/simcom_7000.cpp, vehicle/OVMS.V3/components/simcom/src/simcom_7600.cpp, vehicle/OVMS.V3/components/vehicle/vehicle_poller_vwtp.cpp, vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.cpp, vehicle/OVMS.V3/components/vehicle_fiat500/src/vehicle_fiat500e.cpp, vehicle/OVMS.V3/components/vehicle_mercedesb250e/src/vehicle_mercedesb250e.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/main/ovms.h, vehicle/OVMS.V3/main/ovms_metrics.cpp
With the new warnings activated in ESP-IDF 4+, a `switch`-`case` must now properly and explicitely identify when a fall-through is wanted or is a forgotten `break`.
One way to mark those wanted fall-through is to mark them with a [GCC-specific attribute](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough), a [C++ attribute](https://en.cppreference.com/w/cpp/language/attributes/fallthrough) or even with a specific comment as [documented in the GCC compiler](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough).
We took inspiration from the [Linux Kernel approach](https://elixir.bootlin.com/linux/v5.10/source/include/linux/compiler_attributes.h#L208) to create a macro `FALLTHROUGH;` that should do the proper decoration (either …
=> cleanup warnings about switch case fallthrough

vehicle/OVMS.V3/main/ovms_events.cpp, vehicle/OVMS.V3/main/ovms_events.h
Starting with ESP-IDF v4+, a part of the Event Loop library is deprecated : cf https://docs.espressif.com/projects/esp-idf/en/v4.4.4/esp32/api-reference/system/esp_event_legacy.html for details of the deprecated functions and structures.
This PR rewrites this event loop with the newer esp_event library event loop.
=> ESP-IDF v4+ : replace legacy event loop with esp_event Library Event Loop

vehicle/OVMS.V3/components/dbc/src/dbc.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_renaulttwizy/src/rt_types.h, vehicle/OVMS.V3/components/vehicle_renaultzoe/src/vehicle_renaultzoe.cpp
In ESP-IDF v5+, a compiler change has been made for type `int32_t` and `uint32_t` : Cf https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/gcc.html#int32-t-and-uint32-t-for-xtensa-compiler
This change forces us to update the definition of our `INT` type (which is indirectly based on the `UINT` definition in fatfs), and to update a few definitions here and there.
A distinct PR will tackle with the impact of this change on `printf` format strings.
=> Change definition of `INT` from `int32_t` to `int`

vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.cpp, vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.h, vehicle/OVMS.V3/components/ovms_cellular/src/gsmpppos.cpp, vehicle/OVMS.V3/components/ovms_cellular/src/gsmpppos.h, vehicle/OVMS.V3/main/ovms_events.cpp, vehicle/OVMS.V3/main/ovms_netmanager.cpp, vehicle/OVMS.V3/main/ovms_netmanager.h, vehicle/OVMS.V3/main/ovms_peripherals.cpp
TCP/IP Adapter was the ESP-IDF network interface abstraction component used in versions <= 4.  
Starting with ESP-IDF 4, a new network interface abstraction component appears : ESP-NETIF.  
There is a [porting guide for ESP-IDF 4+](https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32/api-reference/network/tcpip_adapter_migration.html), and a few changes specific to ESP-IDF 5+.
This huge PR tries to stay 3.3 / 4 / 5 compatible and will need to be reviewed and tested.
=> Use ESP-NETIF instead of TCP/IP Adapter

vehicle/OVMS.V3/components/ovms_mdns/src/ovms_mdns.cpp, vehicle/OVMS.V3/components/ovms_mdns/src/ovms_mdns.h
Starting with ESP-IDF v4.1+, `mdns_handle_system_event` [is deprecated](https://github.com/espressif/esp-idf/blob/349385cb645432b17a4f2148bdd0e863136324d1/components/mdns/include/mdns.h#L365)
this change is part of the new event mechanism.
The call is removed, which also removes the necessity to listen on a system event.
=> ESP-IDF v4+ : remove deprecated mdns functions

vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp, vehicle/OVMS.V3/components/vehicle_teslaroadster/src/vehicle_teslaroadster.cpp, vehicle/OVMS.V3/main/console_async.cpp
The field `.use_ref_tick` has been replaced by another one `.source_clk` with a different semantic.
Cf https://docs.espressif.com/projects/esp-idf/en/release-v5.0/esp32/migration-guides/release-5.x/peripherals.html#uart
=> ESP-IDF v5+: changes to uart_config_t

vehicle/OVMS.V3/components/ovms_netlib/src/ovms_nethttp.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duk_http.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duk_util.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duk_vfs.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duktape.cpp, vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp
Undefining MG_ENABLE_SSL (which we had to do during the setup of the ESP-IDF v5 upgrade) show that some modules would not compile any more. We make them work as well as possible.
=> ESP-IDF v5+: dependency on ovms_tls.h / MG_ENABLE_SSL

vehicle/OVMS.V3/components/vehicle/vehicle_poller_isotp.cpp
This is just to please the compiler, as in practice it looks that those variables will not be used without being initialized.
=> fix uninitialized value warning

vehicle/OVMS.V3/components/vehicle_mgev/src/mg_bcm.cpp, vehicle/OVMS.V3/main/ovms_command.cpp, vehicle/OVMS.V3/main/test_framework.cpp
In ESP-IDF 4+, this will trigger a compile error so we add the header.
=> fix missing esp_timer header

vehicle/OVMS.V3/components/vehicle/vehicle.cpp
Message:
```
format '%ld' expects argument of type 'long int', but argument 4 has type 'int'
```
The 2 arguments are of type `int` (not `int32_t`).
=> fix for format error

vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp
CAN Bus needs a pair of includes since ESP-IDF 4+
=> ESP-IDF v5+: CAN bus defines

vehicle/OVMS.V3/components/ovms_location/src/ovms_location.cpp, vehicle/OVMS.V3/components/ovms_location/src/ovms_location.h, vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/main/metrics_standard.cpp, vehicle/OVMS.V3/main/metrics_standard.h
- Simply allowing 'Valet mode' without hardware support gives door detection anyway..
- This adds the ability to have a Valet mode geofence radius from start location.
=> Valet Mode - add default valet mode with simple geofence

vehicle/OVMS.V3/main/ovms_command.cpp
`sys/stat.h` include was missing from `main/ovms_command.cpp`, and it provoked a compilation error - interestingly, only shown when `CONFIG_OVMS_COMP_CELLULAR=n`
Thanks to @jetpax for the notice !
_Cf https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/810#issuecomment-1454437854_
=> add a missing include

vehicle/OVMS.V3/main/ovms.h, vehicle/OVMS.V3/main/ovms_main.cpp
We introduced the dependency on the (official) configuration item `CONFIG_ESP_TASK_WDT` to decide whether (or not) we want to initialize the WDT. In ESP-IDF v5+, it's not possible any more to (re)initialize and already initialized timer, and if `CONFIG_ESP_TASK_WDT` the WDT would have been initialized already during boot.
Note: For some reason, in ESP-IDF v5+, we need to define `CONFIG_ESP_TASK_WDT=n` otherwise it won't work as expected.
=> ESP-IDF v5+: update WatchDogTimer initialization

vehicle/OVMS.V3/components/vehicle_bmwi3/src/vehicle_bmwi3.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniqvfl/src/vehicle_hyundai_ioniqvfl.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp, vehicle/OVMS.V3/components/vehicle_minise/src/vehicle_minise.cpp, vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.cpp, vehicle/OVMS.V3/components/vehicle_smarted/src/ed_can_poll.cpp
This would be needed for stricter compiler in ESP-IDF v5+
=> missing math.h include in some vehicle modules

vehicle/OVMS.V3/components/mcp2515/CMakeLists.txt, vehicle/OVMS.V3/components/ovms_webserver/CMakeLists.txt
Found 2 errors introduced in d71c03091.
Should only impact ESP-IDF v5+ builds, no impact on current ESP-IDF 3.3.4 builds.
=> ESP-IDF v5+: CMakeLists.txt - fixes for mcp2515 / ovms_webserver

vehicle/OVMS.V3/main/ovms_module.cpp
On ESP-IDF v5+ `spi_flash_erase_range` is replaced with `esp_flash_erase_region`, which would need a flash chip `esp_flash_init()` call at some point.
It looks easier to use `esp_partition_erase_range`, which in addition is a little bit higher level, does bounds checking and is recommended for the main SPI Flash Chip.
Cf 
* https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_flash/index.html#overview
* https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_flash/index.html#_CPPv422esp_flash_erase_regionP11esp_flash_t8uint32_t8uint32_t
* https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/partition.html#_CPPv425esp_partition_erase_rangePK15esp_partition_t6size_t6size_t
=> module_perform_factoryreset : use `esp_partition_erase_range` instead of `spi_flash_erase_range`

docs/README.md, docs/source/conf.py, docs/source/requirements.txt
`m2r` project is in archive mode : https://github.com/miyakogi/m2r and there is a warning during plugin installation.   
[`m2r2`](https://pypi.org/project/m2r2/#description) presents itself as a maintained fork of `m2r`:
> M2R2 is a fork of m2r which hasn't been updated for a long time and there's been
> no response from the author about a PR fixing a serious issue that broke several
> pipelines using sphinx3. Every m2r config should work out of the box.
=> Docs: replace deprecated `m2r` plugin with its successor `m2r2`

docs/source/userguide/components.rst, vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/can/src/canlog.cpp, vehicle/OVMS.V3/components/can/src/canlog.h, vehicle/OVMS.V3/components/id_filter/CMakeLists.txt, vehicle/OVMS.V3/components/id_filter/component.mk, vehicle/OVMS.V3/components/id_filter/src/id_filter.cpp, vehicle/OVMS.V3/components/id_filter/src/id_filter.h, vehicle/OVMS.V3/components/id_filter/src/id_include_exclude_filter.cpp, vehicle/OVMS.V3/components/id_filter/src/id_include_exclude_filter.h, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.h
Implement Server v3 metrics filtering with configurable include/exclude list.  See "OVMS Server v3" section of docs/source/userguide/components.rst for details.
A new id_filter component has been factored out of components/can/canlog for use by canlog and the new server v3 metrics filtering functionality.
(see PR #867 for an earlier attempt)
Resolves #344
=> Implement Server v3 metrics filtering

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/main/Kconfig, vehicle/OVMS.V3/main/ovms_netmanager.cpp, vehicle/OVMS.V3/main/ovms_netmanager.h
_Note: This PR won't add any visible feature to current builds, as the ping/ICMP support is only available since ESP-IDFv4.
So the feature will not be enabled for the current (ESP-IDFv3.3.4) builds._
Just like a simplified `ping` command, it will send 4 ICMP echo packets and wait for the reply.
It's not compiled by default, you'll need to enable it in `menuconfig` / `Developer Options` / `Enable netmanager ping support`.
It's a straightforward (and simplified, no handling of any optional arguments) port of ESP-IDF's ICMP echo example: [protocols/icmp_echo](https://github.com/espressif/esp-idf/tree/f404fe96b1/examples/protocols/icmp_echo)
Note: an ugly hack has been introduced (a 4200 ms delay) to prevent the `OVMS#` prompt to interfere with the output.
Without this delay, the output looks …
=> Network: New 'network ping' command to ping (ICMP) hostname or IP address (ESP-IDFv4+ only)

vehicle/OVMS.V3/components/id_filter/CMakeLists.txt
Without having the different paths / files individually quoted, I couldn't compile this component.
=> fix small mistake in id_filter CMakeLists.txt

vehicle/OVMS.V3/main/ovms_metrics.h
I've noticed some compiler errors due to OvmsWriter not being available in ovms_metrics.h when ovms_script.h is not included because duktape is disabled.
=> Fix compilation errors when compiling without javascript runtime

vehicle/OVMS.V3/dependencies.lock
This dependency update is only for ESP-IDF v5+ - it should not impact ESP-IDF v3.3.4 builds.
Cf: 
* https://components.espressif.com/components/espressif/mdns
* https://github.com/espressif/esp-protocols/commits/mdns-v1.0.9
=> ESP-IDF v5+ : upgrade to mdns 1.0.9

vehicle/OVMS.V3/components/console_ssh/src/console_ssh.cpp
ESP-IDF v5+ has more strict requirements and data type changes which necessitates a few tweaks:
* impact of the change of type of uint32_t in `wolfssl`
* workaround for a compilation issue with `wolfssh` (byte)
Both changes are compatible, and not impacting ESP-IDF v3.3.4
=> Fix espv5 compilation `wolfssl` / `wolfssh`

vehicle/OVMS.V3/main/ovms_netmanager.cpp
It's unfortunate but I let this error slip ; and this part was not compiled in my compilation tests.
=> [ESP-IDFv4+] Network: fix duplicate definition in new 'network ping' command

vehicle/OVMS.V3/components/ovms_server_v2/src/ovms_server_v2.cpp, vehicle/OVMS.V3/components/vehicle_renaulttwizy/src/rt_sevcon_faults.cpp, vehicle/OVMS.V3/main/test_framework.cpp
While experimenting with newer ESP-IDF releases (branches v5.0 and v5.1) I found a few more warnings turned into errors, that were easy to fix.
=> Fix warning as errors

vehicle/OVMS.V3/components/vehicle/vehicle.cpp
Default generation of configuration was bad.  Lack of commas and 'yaxis' tag was causing it to crash in the browser.
=> Vehicle - Fix up default generation of dashboard configuration

vehicle/OVMS.V3/components/console_ssh/src/console_ssh.cpp
Recent versions of WolfSSH define a new enum `WS_LOG_CERTMAN` that we need to handle (otherwise we are greeted with a compilation error message).
=> compatibility with WolfSSH >= 1.4.12

vehicle/OVMS.V3/components/console_ssh/src/console_ssh.cpp
Now that wolfssl has been upgraded to a recent version, we can target the latest release of wolfssh.
=> Upgrade wolfssh 1.4.13

vehicle/OVMS.V3/main/ovms_module.cpp
In ESP-IDF 3.3.x builds of OVMS, we're using a fork of ESP-IDF. In this fork, FreeRTOS has been patched with openvehicles/esp-idf@95e43fc2c4360f8126a0985bf037a293bebe3767 to add a `uxMutexesHeld` field in `TaskStatus_t`.
However, in the ESP-IDF >= 4 build we're using mainstream ESP-IDF (for the moment), which does not include this field.
So we adapt the display to handle both cases.
=> ESP-IDF v4+: we do not have uxMutexesHeld any more

vehicle/OVMS.V3/main/CMakeLists.txt, vehicle/OVMS.V3/main/ovms_boot.cpp, vehicle/OVMS.V3/main/ovms_boot.h
* error handling rework (`xt_set_error_handler_callback` is only available in our ESP-IDF 3.3.4 fork.)
* `esp_task_wdt_get_trigger_tasknames()` not available (**feature removed** from ESP-IDF4+ builds) TODO
* first steps to support other archs than XTensa in `boot_data.crash_data`
=> ESP-IDF4+ : crash handler and boot status

vehicle/OVMS.V3/components/can/src/canlog_tcpserver.cpp
First argument is `<host[:port]>`. If port omitted, it is set to `3000`.
=> fix documentation of arguments of tcpserver

vehicle/OVMS.V3/components/ovms_plugins/CMakeLists.txt, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h, vehicle/OVMS.V3/components/vehicle_maxus_euniq56/src/vehicle_me56.cpp
* (specific to ESP-IDF4+) : make `ovms_plugins` compilable with or without `duktape`
* `vehicle_hyundai_ioniq5` had issue when disabling webserver component
* `vehicle_maxus_euniq56` had missing header when disabling webserver component
=> fix a few issues appearing when disabling/enabling components

vehicle/OVMS.V3/components/obd2ecu/src/obd2ecu.cpp
When you reverse the RPM value goes negative, but since that  particular OBD2 value is unsigned, the HUD displays it as out-of-range (for example all 9s).
=> OBD2ECU - Keep RPM positive 

vehicle/OVMS.V3/components/obd2ecu/src/obd2ecu.cpp, vehicle/OVMS.V3/components/obd2ecu/src/obd2ecu.h
Only place incoming CAN entries from the obd2ecu bus into the OBD2ECU queue.  
This can be done by using a callback rather than just providing the queue.
=> OBD2ECU - reduce overload of limited ECU queue

vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.h
When enabling the new location streaming option, OVMS continuously sends modified metric updates even when the vehicles is off. 
For a Nissan Leaf, that is 4-6 metrics every second, which quickly uses up LTE data.
Please find a change that checks the caron value, m_streaming value and takes the minimum next update time based on the other state values.
The change also makes the nested (cond)?action1:action2 code more readable.
=> Disable continuous metric streaming when vehicle is off

vehicle/OVMS.V3/components/vehicle_mgev/docs/index.rst, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mg5.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgzsev2.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgzsev2.hpp
Fix error in documentation to show MG ZS EV Mk2 Standard Range support. Fix Mk2 battery capacity. Change vehicle dropdown to be clearer
=> Fix MK2 battery capacity

vehicle/OVMS.V3/components/vehicle_mgev/src/mg_configuration.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.h
BMS DoD limits were not being updated when Config changed in MG ZS EV (UK/EU). Added code to fix this.
=> Fix bms dod limits

vehicle/OVMS.V3/main/ovms_metrics.cpp
There were a number of 'breaks' missing from switch() statements in  the main UnitConvert functions. Mostly this would have been harmless enough but there were probably some strange edge cases introduced.
=> OVMS Unit Conversion - Add breaks to switches

vehicle/OVMS.V3/components/vehicle_mgev/src/mg_configuration.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_poll_bms.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mg5.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.h, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_a.h, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev_b.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgzsev2.cpp
BMS DoD limits were not being updated when Config changed in the MG ZS EV (UK/EU). Added code to fix this. Save DoD Lower and DoD Upper to MyMetrics instead of MyConfig
=> Fix handling of BMS DoD values

vehicle/OVMS.V3/main/metrics_standard.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
- Adds UnixEpoch, UTCDate and LocalDate metrics as well as a 'Date' group.
- Sets standard metrics m.time.utc to use UTCDate and v.pos.gpstime to use LocalDate
- Conversion between the different Date metrics is unity - it is simply used for displaying and storing the date value.
- JSON Dates now use the standard(ish) Java date format.
=> Metrics - add Date metrics with local/utc printing

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp
Noticed while setting up OVMS for my new 62kWh battery that this option was missing from the webUI. Added it!
=> Add 62kWh option to LEAF webui

docs/source/userguide/metrics.rst, vehicle/OVMS.V3/main/metrics_standard.cpp, vehicle/OVMS.V3/main/metrics_standard.h
Updates doc for m.time.utc, v.e.serv.time and v.p.gpstime to reflect their default display as date.
Changes v.e.ser.time to a DateLocal (from Seconds) metric
=> Date metrics doc & clarify 'Service Time' as local date

vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_can_handler.cpp, vehicle/OVMS.V3/components/vehicle_kianiroev/src/kn_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/ks_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_can_handler.cpp, vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe/src/vehicle_renaultzoe.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/vehicle_renaultzoe_ph2_obd.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp
This is not necessarily essential since moduleid_low is (now) in the state, but I believe it makes more to switch on the received module than the 'expected low'  even though that should amount to the same thing.
=> Vehicle - use moduleid received  instead of 'moduleid_low'

vehicle/OVMS.V3/components/ovms_cellular/src/gsmnmea.cpp, vehicle/OVMS.V3/components/vehicle_mitsubishi/src/mi_commands.cpp, vehicle/OVMS.V3/components/vehicle_mitsubishi/src/vehicle_mitsubishi.h, vehicle/OVMS.V3/components/vehicle_teslaroadster/src/vehicle_teslaroadster.cpp, vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_obd.cpp, vehicle/OVMS.V3/main/metrics_standard.cpp, vehicle/OVMS.V3/main/metrics_standard.h, vehicle/OVMS.V3/main/ovms_housekeeping.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
These commits 
* Implement 64 bit value storage and persisting.
* Implement storing of time values as 64 bit integers and ensure all references to these values are via time_t
Although in the currently used version of  the ESP-IDF libraries time_t is a 32bit integer,  this paves the way for when later versions of ESP-IDF are used that contain 64 bit time_t.
=> Implement 64bit Time storage 

vehicle/OVMS.V3/components/ovms_http/src/ovms_http.cpp
- Was coming up as a warning in later C++ (ignored return value)
=> http - Clear bad buffer if unexpected size.

vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle/vehicle_poller.cpp, vehicle/OVMS.V3/components/vehicle/vehicle_poller_isotp.cpp, vehicle/OVMS.V3/components/vehicle/vehicle_poller_vwtp.cpp, vehicle/OVMS.V3/components/vehicle_boltev/src/vehicle_boltev.cpp, vehicle/OVMS.V3/components/vehicle_boltev/src/vehicle_boltev.h, vehicle/OVMS.V3/components/vehicle_jaguaripace/src/ipace_can_handler.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp, vehicle/OVMS.V3/components/vehicle_voltampera/src/vehicle_voltampera.cpp, vehicle/OVMS.V3/components/vehicle_voltampera/src/vehicle_voltampera.h
The aim here is to move away from vehicle implementations knowing anything about the poll-list pointers, and to move towards a system where there is a function call to 'get the next poll entry'. 
The biggest change here is that it moves a while loop from PollerSend() to a factored NextPollEntry()
-  Factor retrieving of next poll entry
-  Pass in Enum of poll call reason Primary/OnceOff/PollSuccess
-  Clean up resetting of ticker.
-  Introduce PollRunFinished() (as a safe place to check for Poll State changes.)
=> OBD Poller - Cleaner interface to Poll-List and retrieving next entry

vehicle/OVMS.V3/components/ovms_cellular/src/gsmnmea.cpp
- Blank direction will leave the value as it was
- Blank Speed only zeros speed after 10 seconds.
Currently the '10 seconds' is hard-coded and rather arbitrary... but I think better than just always clobbering it as soon as there is a blank speed (which is 'unspecified' rather than 0)
=> Internal GPS - Handle speed/direction missing from data

vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle/vehicle_poller.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_bcm.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/mg_software_versions.cpp, vehicle/OVMS.V3/components/vehicle_mgev/src/vehicle_mgev.cpp
This allows us to move the poller list to 'private' and away from access by vehicle implementations.
=> OBD Poller - Implement Pause/Resume of polling

vehicle/OVMS.V3/main/ovms_metrics.h
This is needed for later compilers which warn that  virtual SetValue and operator=  cause these methods to be hidden when reintroduced (not overridden)
=> Metrics - Make sure overloaded SetValue / operator= are visible at top level

vehicle/OVMS.V3/components/esp32can/src/esp32can.cpp, vehicle/OVMS.V3/components/vehicle/vehicle_poller_vwtp.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/kia_common.h, vehicle/OVMS.V3/components/vehicle_kiasoulev/src/vehicle_kiasoulev.cpp, vehicle/OVMS.V3/components/vehicle_renaulttwizy/src/rt_sevcon_faults.cpp, vehicle/OVMS.V3/main/test_framework.cpp
Fix warnings that have been introduced by the switch to C++20 compiler in ESP-IDF v5+.
* Infinite recursion detection
* Deprecated implicit cast of enum to float
* Transition of implicit capture of this (deprecated) to explicit capture of this
* Enhanced 'unused result' detection in macro expansion.
* A deprecated 'nullptr' conversion issue
=> Various fixes related to C++20 compiler

vehicle/OVMS.V3/components/canopen/src/canopen.h
- CanOpenworker is now 'final' to remove warning for missing virtual destructor, which is not required despite being accessed via pointer. (Warning in C++20)
- SendNMT() etc were overloaded not overridden and so no need to make them virtual (yet?)  (Visibility warning in C++20)
- Remove other (as yet?) unnecessary virtual specifiers
=> CanOpen - Fix warnings  introduced by newer compiler standard

README.md
Fasttech is not a distributor of OVMS any more since a longer time but still listed here.
=> Update README.md - remove fasttech

README.md
The current hardware version 3.3 is the one with the highest cost. Many people report on the internet that they do not get the OVMS because of the high cost. Its not that affordable for many people so just remove the comment about the price because it does not add any benefits. The people see the price at the distributor and decide on their own if they can afford it. Hardware version 3.3 have dual certification and the modem can be used worldwide. Also it supports 2g, 3g and 4g networking.
=> Update README.md - update description to represent hardware version 3.3

README.md
https://e-mobility-driving-solutions.com is selling OVMS for more then a year and is currently unlisted
=> Update README.md - add missing distributor from germany

vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/main/Kconfig
Makes sure that the Frame RX functions are either being called fromthe Poller task or from a separate vehicle task if there is no poller
=> Vehicle - Make sure RX functions are being called from a Task

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Float charging can be as low as 12.9V and create nuisance logging going between 12.9 and 13V
=> NL: Avoid flipflop of 12v charging metric

vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp
Was only obeying throttling in the protocol (*tp) handling code.
Obey it at other times. too.
=> Vehicle Poller - Obey throttling

vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h
The poller state used to get reset to 0 ensuring it fired then.
This restores that behaviour.
=> Poller - Make sure state 0 happens on the first run after being reset

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h, vehicle/OVMS.V3/main/ovms_utils.h
Splits the logging for the Poller into logs that would happen in the RX/TX Tasks (which can cause all sorts of issues)
and those that would happen in the poller task (which can be still problematic if response needs to be really quick).
=> Poller reduce logging noise

vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h
Adds Ioniq 5 shortname - the menu name was getting a little long after the adding of EV6
=> Ioniq5 shortname

vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h, vehicle/OVMS.V3/main/ovms_utils.h
- Improve averaging algorithm to include better start-up (but still fast)
- Shorten message and split if necessary.
- Reset averages on vehicle.on and charging.start
=> Poller timer improvements

vehicle/OVMS.V3/components/microrl/microrl.c, vehicle/OVMS.V3/components/microrl/microrl.h, vehicle/OVMS.V3/main/ovms_command.cpp, vehicle/OVMS.V3/main/ovms_command.h, vehicle/OVMS.V3/main/ovms_console.cpp, vehicle/OVMS.V3/main/ovms_console.h, vehicle/OVMS.V3/main/ovms_vfs.cpp
- Gets the completion length via the callback to count for dropped entries
- Supports not adding space when a completion item (path) is not 'complete'
=> Console - Improve completion support for paths

vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller_isotp.cpp
In ESP-IDF v5+, a compiler change has been made for type int32_t and uint32_t : Cf https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/gcc.html#int32-t-and-uint32-t-for-xtensa-compiler
This change forces us to update the `printf. format strings and use, as much as possible, the [PRI... portable format constants](https://en.cppreference.com/w/cpp/types/integer)
In addition, a constant in `Atomic_Increment()` call needed to change in order to compile with ESP-IDF v5+ compiler.
=> Poller - int32_t format strings changes

vehicle/OVMS.V3/components/vehicle/CMakeLists.txt, vehicle/OVMS.V3/components/vehicle/vehicle.cpp
Following 43ca259 and the split of the `poller` component, a change is needed to properly compile with ESP-IDF v5+.
A compilation issue is also fixed.
=> Vehicle - enable compilation with ESP-IDF v5+

vehicle/OVMS.V3/components/ovms_webserver/src/web_framework.cpp
`INT64_FMT` replaced with `PRId64` because `INT64_FMT` is a Mongoose 6.x specific define, and this define does not exist any more in Mongoose 7.x releases.
=> Ovms_Webserver - int64_t format strings changes

vehicle/OVMS.V3/components/vehicle_vweup/src/vweup_t26.cpp
The compiler in ESP-IDF v5+ is very sensitive to detecting potential issue. Here, an indentation could be interpreted by the human reader as if an `if` block was encompassing a whole indented block.
The fix here is either to remove the indentation, or to add curly braces to explicitely delimit the block managed by the `if` condition.
The indentation was removed.
**Note** : I erred on the safe side by remove the indentation, so that it compiles the same way it does on ESP-IDF v3. However, as I'm note familiar with the code and the intention of the `if` condition, I'd appreciate a full review of this block of code by a more knowledgeable person than me. Thanks :-)
=> Vehicle_Vweup - fix a compilation issue

vehicle/OVMS.V3/components/esp32bluetooth/CMakeLists.txt
This prevent building with ESP-IDF 5+ ; should have no regression at all in current ESP-IDF v3 builds.
=> esp32bluetooth: fix compilation with ESP-IDF cmake-based build system (v4+)

vehicle/OVMS.V3/main/ovms_peripherals.cpp
A missing `esp_netif.h` header for ESP-IDF v4+ in `ovms_peripherals.cpp`
=> ESP-IDFv4+ : fix missing header

vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.cpp, vehicle/OVMS.V3/components/esp32wifi/src/esp32wifi.h, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.h, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.h, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp, vehicle/OVMS.V3/main/metrics_standard.cpp, vehicle/OVMS.V3/main/metrics_standard.h, vehicle/OVMS.V3/main/ovms_netmanager.cpp, vehicle/OVMS.V3/main/ovms_netmanager.h
This PR introduces a safeguard to prevent the device from connecting to server v3 if there is a cellular or Wi-Fi connection that is not yet fully established.
For each connection type, the device checks whether the OVMS has been assigned an IP address or if the cellular connection (netMode + mux + ppp) is complete. It also takes into consideration thresholds for good and bad connection and does not attempt a connection whenever there is no good signal. 
If the connection is established but remains unready for a specified duration, the device will assume a failure has occurred and will automatically restart. This can also be disable via the config ("network", "reboot.no.connection") and is false by default.
Server v3 does not connect if less than 10 seconds of a "good " connection have …
=> Ensure Network Stability Before Server Connection

vehicle/OVMS.V3/main/console_async.cpp
Adds some clarification to a couple of the know error types in the logs.
=> Async Errors - Improve Frame/Parity error reporting

vehicle/OVMS.V3/components/vehicle_maxus_euniq6/CMakeLists.txt, vehicle/OVMS.V3/components/vehicle_maxus_euniq6/component.mk, vehicle/OVMS.V3/components/vehicle_maxus_euniq6/src/vehicle_me6.cpp, vehicle/OVMS.V3/components/vehicle_maxus_euniq6/src/vehicle_me6.h, vehicle/OVMS.V3/main/Kconfig
Purpose: 
Initialize support for Maxus Euniq6 model. 
Features included: 
- Speed
- SOC
- Odometer
- ON/AWAKE status
- Vehicle lock/unlock status. 
Notes: 
Noticed there already is a Maxus Euniq5 with 6 seats model but the can bus communication is quite different. So thought it would be best to propose adding a new model instead of modifying the existing one.
=> Maxus Euniq 6 - Initializing module.  

vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h, vehicle/OVMS.V3/main/ovms_utils.h
- Use short(4) and long(8) smoothed average comparison
- Detects a dip while 12V charging as well.
- Only polls while charging if it detects dip or after a longer period
- Factor out to functions
=> Ioniq 5 - Simplify & Improve 12V monitor

docs/source/userguide/events.rst, docs/source/userguide/scripting.rst, vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle/vehicle_duktape.cpp, vehicle/OVMS.V3/components/vehicle/vehicle_shell.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_commands.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h, vehicle/OVMS.V3/main/ovms_housekeeping.cpp, vehicle/OVMS.V3/main/ovms_housekeeping.h, vehicle/OVMS.V3/main/ovms_utils.h
Moved the battery monitor from the Ioniq5 implementation.
Added internal support for enable/disable and extended run-time config.
Add duktape support for aux battery monitor
Add cli support as well.
=> Add Aux 12v battery monitor to vehicle class  (with scripting and duktape intf)

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.h, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp
OVMS is a brilliant system, but I noticed that it was sending MQTT messages every minute, even when configured with updatetimes that were much longer than that. This activity consumes Hologram allowance and power unnecessarily.
The first step in fixing this is to filter out "clock" events, on the basis that they are of no use to anyone:
2024-11-10T22:52:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event', ... (10 bytes))
2024-11-10T22:52:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event/clock/2252', ... (0 bytes))
2024-11-10T22:53:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event', ... (10 bytes))
2024-11-10T22:53:00: Received PUBLISH from leaf (d0, q0, r0, m0, 'ovms/event/clock/2253', ... (0 bytes))
2024-11-10T22:54:00: Received PUBLISH from leaf (d0, q0, r0, …
=> Fix Server V3 client sending messages every minute

vehicle/OVMS.V3/components/can/src/can.cpp, vehicle/OVMS.V3/components/dbc/src/dbc_app.cpp, vehicle/OVMS.V3/components/dbc/src/dbc_app.h
This adds completion for
- the loaded dbc-file identifiers. 
- the baud and dbc identifier in CAN operations
=> DBC Files - implement/improve completion for DBC files and identifier

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/dbc/src/dbc.cpp, vehicle/OVMS.V3/components/dbc/src/dbc.h, vehicle/OVMS.V3/components/dbc/src/dbc_number.cpp, vehicle/OVMS.V3/components/dbc/src/dbc_number.h, vehicle/OVMS.V3/components/retools/src/retools.cpp, vehicle/OVMS.V3/components/vehicle_dbc/src/vehicle_dbc.cpp, vehicle/OVMS.V3/main/ovms_metrics.cpp, vehicle/OVMS.V3/main/ovms_metrics.h
Uses the units in the DBC file, and converts them to Ovms Units so unit conversions can be done when setting the metric values.
Supports the ovms metric name and metric label.
There is some re-factoring done here of the Decode function pulling it back to the dbcFile
=> Dbc use metric units when setting values

vehicle/OVMS.V3/components/can/src/can.h, vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h
- Add mutexes for handling timing.  Keeping locks as small as possible even when reporting.
- Add non-blocking mutex for filters on incoming RX messages to poll
=> Poller tweaks for handling queue getting overrun

vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/docs/index.rst, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/BCM_pids.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/EVC_pids.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/HVAC_pids.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/INV_pids.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/LBC_pids.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/UCM_pids.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/ph2_poller.h, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/rz2_commands.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/rz2_web.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/vehicle_renaultzoe_ph2_obd.cpp, vehicle/OVMS.V3/components/vehicle_renaultzoe_ph2_obd/src/vehicle_renaultzoe_ph2_obd.h
code:
- reformat code for better readability
- remove tabstop and replace it with whitespace
fix:
- correct 12v current and bus state after charge stopped while plugged in
- SoH / CaC handling while runtime instead of one-shot after config
- cell voltage readings (factor was wrong, voltage was too high)
update:
- update readme for TCU removal information, V-CAN tapping and feature list
- significantly improve "bms status" output reading
- code comments
removal:
- remove unneccessary aux power gauges
add:
- added battery health text
- added usable battery capacity (kWh) depends on SoC, SoH
- added 12V charger power value
- added CAN2 interface for V-CAN connection
- added commands for ClimateControl and HomeLink button 1 (because App not showing AC button)
- added pre-heat capability …
=> Update and expand functionality of zoe ph2 integration

vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h
A few fixes for locking and logging in the poller.
- There was a call missing in shutdown
- Some of the logging was moved behind the poller flag.
- Fixed timeouts to use the pdMS_TO_TICKS macro
- Put some timeouts on some locks.
- block some calls in shutdown (to reduce the chance of deleting a poller begin used in the shutdown process.
=> Poller fix locking

vehicle/OVMS.V3/components/can/src/can.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
Includes option to suppress power-down of Can busses for the Leave vehicle module
=> Add the option to avoid powering off Can busses on powerdown

vehicle/OVMS.V3/components/ovms_cellular/src/gsmmux.cpp, vehicle/OVMS.V3/components/ovms_cellular/src/gsmnmea.cpp, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.h, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular_modem_driver.cpp, vehicle/OVMS.V3/components/simcom/CMakeLists.txt, vehicle/OVMS.V3/components/simcom/src/simcom_7000.cpp, vehicle/OVMS.V3/components/simcom/src/simcom_7600.cpp, vehicle/OVMS.V3/components/simcom/src/simcom_7670.cpp, vehicle/OVMS.V3/components/simcom/src/simcom_7670.h, vehicle/OVMS.V3/components/simcom/src/simcom_powering.cpp, vehicle/OVMS.V3/components/simcom/src/simcom_powering.h
Add support for Simcom 7670 modem and GNSS.
Streamline the powering of the Simcom modems during powering on/off and power cycling.
=> Simcom 7670 support and updated Simcom powering

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/dbc/src/dbc.cpp, vehicle/OVMS.V3/components/dbc/src/dbc.h, vehicle/OVMS.V3/components/dbc/src/dbc_app.cpp, vehicle/OVMS.V3/components/dbc/src/dbc_parser.y, vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h, vehicle/OVMS.V3/components/retools/src/retools.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle_dbc/src/vehicle_dbc.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/hif_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.cpp, vehicle/OVMS.V3/components/vehicle_hyundai_ioniq5/src/vehicle_hyundai_ioniq5.h
- moves DBC handling to poller object.
- Supports extended multiplex attributes (allows for more complex states)
- Supports Unit specifiers for metrics
- Supports list  specifiers to assign state string metric values from an integer.
- Abstracts setting metric for future support of more complex metrics.  The big example I want to tackle is so the battery cells (v, temp) are stored in a way that would allow for the averages etc to be recorded.
=>  DBC - Implement extended multiplexing

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/vehicle/vehicle.cpp
Use the 'long' average for 'Low' and 'Charging' related states.
Register the parameters for setting low / charging thresholds for the battery monitor. (Was already implemented in the command)
`vehicle aux monitor enable 11.1 14.5`
=> Battery monitor fixes

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
The old Leaf from 2012 has no "User SOC" (aka instrument/dashboard SOC) nor max_gid value from BMS at least for now, so socnewcar in config settings must be used to set the real max gid value, to get a calculated SoC from this. 
But max_gids custom metric and battery capacity will never be set, because CAN message for battery detecting is missing. So if socnewcar is choosen the max_gids metric and battery capacity will be set from config. 
This enables ranges calculation otherwise all three values stay at zero.
=> NL: 2012 - Fix missing max_gids from config and battery capacity derrived from it

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp
This PR re-arranges the tire pressure monitor sampling order
Fixes #1070 , user reported bug
Rear axle measurements are swapped
=> Nissan LEAF: Fix order of tire pressure sensors

vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
fixed wrong data for Ambient light (copy paste > false edited)
added Digital Speedometer swap options (km/h <> mph <> off)
=> smartEQ: Hotfix DDT4all

vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
smart EQ:
DDT4all revised:
- DDT4all must now be reactivated each time; each activation is active for 5 minutes.
- Activate DDT4all = xsq ddt4all 999, after which you can execute further commands.
- DDT4all blocking logic error fixed; even though the DDT4all option was deactivated, the command could still be executed.
Added a warning for unlocked doors when the vehicle is parked. This option can be activated/deactivated via the Web UI features or in App #16.
variables were renamed so that they can be better assigned to the function.
=> smart EQ: reworked DDT4all

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/nl_web.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
two changes:
- update divisor for calculating actual km/h speed value from can1 0x284 message
- cast uint16_t raw speed value to float before dividing (to avoid dropping the decimal part of the speed value)
---
the new divisor for calculating km/h speed value was validated by eyeballing the standard OBD-II PID for vehicle speed from Car Scanner and comparing it with a custom OVMS dashboard with `v.p.gpsspeed` and `v.p.speed` on a straight, flat road with cruise control on.
it *is* significantly lower (by approx 10%) compared to the speedometer speed, but this is likely due to Nissan (and many others) deliberately overstating speedo speed to comply with [UNECE Regulation No.39](https://unece.org/sites/default/files/2024-04/GRSG-127-12e.pdf) (see point 5.4 on page 8).
the vehicle itself is …
=> Nissan LEAF: improve v.p.speed accuracy and precision

vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp, vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.h
probably best used with #1144 for accurate trip odometer values
this is basically the same as what's being done for the MG EVs, and appears to be reasonably accurate (+/- 1%) when comparing to GPS tracks (recorded on a phone, dual-band GNSS, 1Hz, ~45km across 3 tracks). of course, this depends on having accurate speed measurements, hence #1144
=> Nissan LEAF: derive v.pos.trip from speed

vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp
this fixes a bug where:
- `m.net.type` starts off as "none", before modem IP link is up
- modem manages to register, and we get an AT+CSQ response w/ the signal strength
- `modem::SetSignalQuality()` is called, but `m.net.sq`/`m.net.good.sq` is not updated because `m.net.type` is not "modem" (yet)
- modem IP link comes up, `m.net.type` gets set to "modem", `modem::UpdateNetMetrics()` gets called
- but `m.net.good.sq` is not updated if signal strength doesn't change (caused by `m_sq != newsq` check in `modem::SetSignalQuality()`)
- until signal strength or network type changes to "wifi", `m.net.good.sq` will remain undefined
in this scenario, if the signal strength stays the same for an extended period of time, then `m.net.good.sq` will remain undefined, causing Server v3 to not connect …
=> fix(ovms_cellular): update `m.net.good.sq` in `UpdateNetMetrics()`

vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
- Added a 45-second delay between DDT4all command executions.
- Added a switch to enable/disable the trip reset notification.
- Added two DDT4all codes
=> smart EQ: DDT4all command execution delay

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.h, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
An option has been added to re-activate GPS for position update at intervals when GPS pause while parked is active, allowing the theft and towing alert to issue a warning.
For smart EQ, if the GPS off function is enabled in Cellular, the smart EQ GPS on/off function will be deactivated.
=> GPS parking off re-activate by default for 5 minutes

docs/source/userguide/scripting.rst, vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/dbc/src/dbc.cpp, vehicle/OVMS.V3/components/dbc/src/dbc.h, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duk_http.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duk_vfs.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duktape.cpp, vehicle/OVMS.V3/components/ovms_script/srcduk/ovms_duktape.h, vehicle/OVMS.V3/components/poller/src/vehicle_poller.cpp, vehicle/OVMS.V3/components/poller/src/vehicle_poller.h, vehicle/OVMS.V3/components/poller/src/vehicle_poller_isotp.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.cpp, vehicle/OVMS.V3/components/vehicle/vehicle.h, vehicle/OVMS.V3/components/vehicle/vehicle_duktape.cpp
This series of commits adds various objects and commands for dealing with the bus and polled lists from a Duktape script.
It adds: 
* basic Bus management (Register/PowerDown) 
* Adding(/Removing) a poll list to the system poller.
* The list is represented by a series of 'send' / 'decode' functions
* The decode functionality leverages the already existing DBC decoding. Either by
* Transferring a version of the packet consistent with DBC multi-packet decoding to an existing loaded dbc file
* Create an internal dbc decoding structure that decodes against the payload-only version of the multi-packet ISOTP.  The fact that the DBC decoding is used internally is not important (only in that it avoids duplication).
* Various actions to control the poll state.
* Support for once-off polls with a …
=> Duktape add objects & commands for scripting polling lists

vehicle/OVMS.V3/components/dbc/src/dbc_parser.y
There are some warnings in the %type definitions for yacc which I believe this fixes.
I'm not knowledgeable about  yacc/flex files, however I believe this is a valid fix.
=> DBC Parser - Fix yacc warnings

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp, vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.h, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp
- Fixed job queue overflow
- Limited to 20 readings per call
- Prioritized optional GPS tracking readings
- Optimized Ticker1
- Disabled some interval times/conditions in Ticker1; there are simply too many without use
based on PR is #1195
=> server V3: fixed job queue overflow

vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp
Added a check to ensure at least 7 fields are present in the climate data payload, logging an error and returning early if not. Replaced sprintf with snprintf and increased buffer size for safer string formatting in two locations.
=> smart EQ: Add climate data payload validation and buffer safety

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.cpp, vehicle/OVMS.V3/components/ovms_cellular/src/ovms_cellular.h, vehicle/OVMS.V3/components/ovms_webserver/src/web_cfg.cpp
Introduces a new configuration option to power on GPS for a set time when the vehicle awakes from parking, reducing time to first GPS fix. Updates the modem logic, configuration handling, and web UI to support the new [modem] enable.gps.awake setting.
=> Add GPS auto start on vehicle awake option

vehicle/OVMS.V3/components/ovms_server_v3/src/ovms_server_v3.cpp
Reduced connection retry interval from 60 to 30 seconds and improved jitter logic for more robust network reconnection. Enhanced event handling to avoid redundant metric transmissions and added detailed logging for network state changes and retry attempts. Also made jitter selection more tolerant and clarified connect/retry conditions.
=> Server V3: Improve connection retry and jitter handling

vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
Introduces a REQUIRE_LEN macro for consistent reply length checks and logging, and applies it throughout poll reply handlers to improve robustness. Refactors and extends BMS state parsing to match updated data layout, adds new poll replies and metrics for vehicle state and underhood status, and updates polling intervals and PID definitions for improved accuracy. Removes unused or redundant poll reply handlers, cleans up metric initialization, and improves value sanity checks and bounds in several places.
=> Refactor SmartEQ poll reply handling and metrics

vehicle/OVMS.V3/changes.txt, vehicle/OVMS.V3/components/vehicle_smarteq/docs/index.rst, vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_can_poll.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/eq_web.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.cpp, vehicle/OVMS.V3/components/vehicle_smarteq/src/vehicle_smarteq.h
Improved CAN poll reply and frame parsing with length/DLC guards to prevent processing of incomplete data and added switch fallthrough corrections. Introduced automatic 12V ADC factor recalculation using BMS 12V voltage, with configurable offset and web UI controls. Updated documentation and web UI to reflect new features and configuration options.
combined #1213 and #1214
I simply combined the updates. Unfortunately, separating them is no longer so easy.
=> smart: EQ: Harden CAN poll parsing and add 12V ADC recalibration
